/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup Endpoint */
        post: operations["signup_endpoint_v1_accounts_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email Endpoint */
        post: operations["verify_email_endpoint_v1_accounts_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Verification Endpoint
         * @description Always returns 202, whether or not the email is registered.
         *
         *     Silently no-ops when the address doesn't map to an unverified
         *     password-backed user. Same enumeration-resistant shape as
         *     ``POST /v1/auth/password-reset/request``. Reuses the password-reset
         *     rate-limit bucket since the abuse profile is identical (anonymous +
         *     triggers an outbound email per request).
         */
        post: operations["resend_verification_endpoint_v1_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Password Reset Endpoint
         * @description Always returns 202, regardless of whether the email is registered.
         *
         *     The reset email is sent only when a matching user exists; otherwise
         *     the endpoint is a silent no-op. This deliberate symmetry stops the
         *     endpoint from being used to enumerate registered addresses.
         */
        post: operations["request_password_reset_endpoint_v1_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Password Reset Endpoint */
        post: operations["confirm_password_reset_endpoint_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Endpoint */
        post: operations["login_endpoint_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout Endpoint
         * @description Clear the session cookie and revoke its DB row if valid.
         *
         *     Unauthenticated — calling with a stale cookie just clears it.
         */
        post: operations["logout_endpoint_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me Endpoint */
        get: operations["me_endpoint_v1_accounts_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/oauth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Oauth Providers Endpoint
         * @description Public — which OAuth providers the portal should render buttons for.
         */
        get: operations["oauth_providers_endpoint_v1_auth_oauth_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/oauth/{provider}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Login Endpoint */
        get: operations["oauth_login_endpoint_v1_auth_oauth__provider__login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Callback Endpoint */
        get: operations["oauth_callback_endpoint_v1_auth_oauth__provider__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/me/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Keys Endpoint */
        get: operations["list_api_keys_endpoint_v1_accounts_me_api_keys_get"];
        put?: never;
        /** Create Api Key Endpoint */
        post: operations["create_api_key_endpoint_v1_accounts_me_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/me/api-keys/{api_key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Api Key Endpoint */
        delete: operations["revoke_api_key_endpoint_v1_accounts_me_api_keys__api_key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/me/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Balance */
        get: operations["get_my_balance_v1_accounts_me_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/me/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Ledger */
        get: operations["get_my_ledger_v1_accounts_me_ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Topup User */
        post: operations["admin_topup_user_v1_admin_users__user_id__topup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending Users Endpoint */
        get: operations["list_pending_users_endpoint_v1_admin_users_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Users Endpoint */
        get: operations["list_all_users_endpoint_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve User Endpoint */
        post: operations["approve_user_endpoint_v1_admin_users__user_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}/billing-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Billing Config Endpoint */
        get: operations["get_billing_config_endpoint_v1_admin_users__user_id__billing_config_get"];
        /** Put Billing Config Endpoint */
        put: operations["put_billing_config_endpoint_v1_admin_users__user_id__billing_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/deposit-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deposit Snapshots Endpoint */
        get: operations["list_deposit_snapshots_endpoint_v1_admin_deposit_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Entries Endpoint */
        get: operations["list_audit_entries_endpoint_v1_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Verification Endpoint
         * @description Re-send the email-verification message to an unverified user.
         */
        post: operations["resend_verification_endpoint_v1_admin_users__user_id__resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/discovery/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin List Capabilities Endpoint
         * @description Operator view of the live capability catalog.
         *
         *     Proxies through the same service layer the app-dev /v1/capabilities
         *     endpoint uses; the only difference is the auth model (bearer token
         *     instead of API-key/session). No business logic duplication.
         */
        get: operations["admin_list_capabilities_endpoint_v1_admin_discovery_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/discovery/orchestrators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Orchestrators Endpoint */
        get: operations["admin_list_orchestrators_endpoint_v1_admin_discovery_orchestrators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Capabilities Endpoint */
        get: operations["list_capabilities_endpoint_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orchestrators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orchestrators Endpoint */
        get: operations["list_orchestrators_endpoint_v1_orchestrators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Select Route Endpoint
         * @description Convenience: returns a single ranked route for (capability, offering).
         */
        get: operations["select_route_endpoint_v1_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/mint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint Payment Endpoint */
        post: operations["mint_payment_endpoint_v1_payments_mint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Payments */
        get: operations["list_my_payments_v1_payments_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payments/{work_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Payment Endpoint */
        get: operations["get_payment_endpoint_v1_payments__work_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Usage Endpoint */
        post: operations["report_usage_endpoint_v1_usage_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUserList */
        AdminUserList: {
            /** Items */
            items: components["schemas"]["AdminUserView"][];
            /** Total */
            total: number;
        };
        /**
         * AdminUserView
         * @description Admin listing row: identity + approval + balance, no secrets.
         */
        AdminUserView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Email Verified At */
            email_verified_at: string | null;
            /** Approved */
            approved: boolean;
            /** Balance Wei */
            balance_wei: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ApiKeyList
         * @description Outbound: list of a user's keys.
         */
        ApiKeyList: {
            /** Items */
            items: components["schemas"]["ApiKeyView"][];
        };
        /**
         * ApiKeyView
         * @description The non-secret view of a key.
         */
        ApiKeyView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Prefix */
            prefix: string;
            /** Label */
            label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
        };
        /**
         * ApprovedUserView
         * @description A user with an active approval.
         */
        ApprovedUserView: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
            /**
             * Operator Id
             * Format: uuid
             */
            operator_id: string;
        };
        /** AuditEntryList */
        AuditEntryList: {
            /** Items */
            items: components["schemas"]["AuditEntryView"][];
        };
        /**
         * AuditEntryView
         * @description One row of operator_audit, joined with the operator + target emails.
         */
        AuditEntryView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Operator Email */
            operator_email: string;
            /** Action */
            action: string;
            /** Target User Email */
            target_user_email: string | null;
            /** Target User Id */
            target_user_id: string | null;
            /** Params */
            params: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * BalanceView
         * @description The user-facing snapshot of credit state.
         */
        BalanceView: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Amount Wei */
            amount_wei: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * BillingConfigResponse
         * @description Outbound: per-user config plus the effective values.
         */
        BillingConfigResponse: {
            config: components["schemas"]["BillingConfigView"];
            effective: components["schemas"]["EffectiveBillingConfigView"];
        };
        /**
         * BillingConfigUpdate
         * @description Inbound: ``PUT /v1/admin/users/{id}/billing-config``.
         *
         *     Send `null` to clear an override and inherit the default; send an
         *     integer to set/replace it.
         */
        BillingConfigUpdate: {
            /** Spend Period Seconds */
            spend_period_seconds?: number | null;
            /** Spend Period Cap Wei */
            spend_period_cap_wei?: number | null;
            /** Auto Replenish Increment Wei */
            auto_replenish_increment_wei?: number | null;
            /** Auto Replenish Threshold Wei */
            auto_replenish_threshold_wei?: number | null;
        };
        /**
         * BillingConfigView
         * @description Per-user billing config (null = inherit default).
         */
        BillingConfigView: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Spend Period Seconds */
            spend_period_seconds: number | null;
            /** Spend Period Cap Wei */
            spend_period_cap_wei: number | null;
            /** Auto Replenish Increment Wei */
            auto_replenish_increment_wei: number | null;
            /** Auto Replenish Threshold Wei */
            auto_replenish_threshold_wei: number | null;
        };
        /** CapabilityList */
        CapabilityList: {
            /** Items */
            items: components["schemas"]["CapabilityView"][];
        };
        /** CapabilityView */
        CapabilityView: {
            /** Name */
            name: string;
            /** Work Unit */
            work_unit: string | null;
            /** Offerings */
            offerings: components["schemas"]["OfferingView"][];
        };
        /**
         * ConfirmPasswordResetRequest
         * @description Inbound: ``POST /v1/auth/password-reset/confirm``.
         */
        ConfirmPasswordResetRequest: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /**
         * CreateApiKeyRequest
         * @description Inbound: ``POST /v1/accounts/me/api-keys``.
         */
        CreateApiKeyRequest: {
            /** Label */
            label: string;
        };
        /**
         * CreateApiKeyResponse
         * @description Outbound: includes the raw key one time only.
         */
        CreateApiKeyResponse: {
            key: components["schemas"]["ApiKeyView"];
            /**
             * Raw Key
             * @description Shown only at creation; Livepeer Open Clearinghouse cannot recover it later
             */
            raw_key: string;
        };
        /** DepositSnapshotList */
        DepositSnapshotList: {
            /** Items */
            items: components["schemas"]["DepositSnapshotView"][];
        };
        /**
         * DepositSnapshotView
         * @description One row from the periodic payment-daemon deposit poll.
         */
        DepositSnapshotView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Taken At
             * Format: date-time
             */
            taken_at: string;
            /** Deposit Wei */
            deposit_wei: number;
            /** Reserve Wei */
            reserve_wei: number;
            /** Withdraw Round */
            withdraw_round: number;
        };
        /**
         * EffectiveBillingConfigView
         * @description The values that would be applied right now (overrides + defaults).
         */
        EffectiveBillingConfigView: {
            /** Spend Period Seconds */
            spend_period_seconds: number;
            /** Spend Period Cap Wei */
            spend_period_cap_wei: number;
            /** Auto Replenish Increment Wei */
            auto_replenish_increment_wei: number;
            /** Auto Replenish Threshold Wei */
            auto_replenish_threshold_wei: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LedgerEntryView
         * @description One row of the credit ledger (audit history).
         */
        LedgerEntryView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Delta Wei */
            delta_wei: string;
            /** Reason */
            reason: string;
            /** Related Payment Id */
            related_payment_id: string | null;
            /** Related Topup Id */
            related_topup_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LedgerPage */
        LedgerPage: {
            /** Items */
            items: components["schemas"]["LedgerEntryView"][];
        };
        /**
         * LoginRequest
         * @description Inbound: ``POST /v1/auth/login``.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description Outbound: ``POST /v1/auth/login`` success.
         *
         *     The session token is delivered via cookie; the body just confirms.
         */
        LoginResponse: {
            user: components["schemas"]["UserResponse"];
        };
        /**
         * MintPaymentRequest
         * @description Inbound: ``POST /v1/payments/mint``.
         */
        MintPaymentRequest: {
            /** Capability */
            capability: string;
            /** Offering */
            offering: string;
            /** Work Units */
            work_units: number;
        };
        /**
         * MintPaymentResponse
         * @description Outbound: ``POST /v1/payments/mint`` success.
         */
        MintPaymentResponse: {
            /**
             * Payment Id
             * Format: uuid
             */
            payment_id: string;
            /** Work Id */
            work_id: string;
            /**
             * Payment Bytes
             * @description Base64-encoded; goes in Livepeer-Payment header
             */
            payment_bytes: string;
            /** Expected Value Wei */
            expected_value_wei: string;
            /** Funded Value Wei */
            funded_value_wei: string;
            /** Recipient Eth Address */
            recipient_eth_address: string;
            /** Capability */
            capability: string;
            /** Offering */
            offering: string;
            /** Work Units Requested */
            work_units_requested: number;
        };
        /** OfferingView */
        OfferingView: {
            /** Id */
            id: string;
            /** Price Per Work Unit Wei */
            price_per_work_unit_wei: string | null;
            /** Work Unit */
            work_unit: string | null;
        };
        /** OrchestratorList */
        OrchestratorList: {
            /** Items */
            items: components["schemas"]["OrchestratorView"][];
        };
        /** OrchestratorView */
        OrchestratorView: {
            /** Eth Address */
            eth_address: string;
            /** Worker Url */
            worker_url: string;
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityView"][];
            /** Signature Status */
            signature_status: string;
            /** Freshness Status */
            freshness_status: string;
        };
        /** PaymentList */
        PaymentList: {
            /** Items */
            items: components["schemas"]["PaymentView"][];
        };
        /**
         * PaymentView
         * @description Outbound: a single payment row in user-facing JSON.
         */
        PaymentView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Work Id */
            work_id: string;
            /** Recipient Eth Address */
            recipient_eth_address: string;
            /** Capability */
            capability: string;
            /** Offering */
            offering: string;
            /** Work Units Requested */
            work_units_requested: number;
            /** Funded Value Wei */
            funded_value_wei: string;
            /** Expected Value Wei */
            expected_value_wei: string;
            /** Reserved Wei */
            reserved_wei: string;
            /** Refunded Wei */
            refunded_wei: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PendingUserList */
        PendingUserList: {
            /** Items */
            items: components["schemas"]["PendingUserView"][];
        };
        /**
         * PendingUserView
         * @description A user not yet approved.
         */
        PendingUserView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Email Verified At */
            email_verified_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReportUsageRequest
         * @description Inbound: ``POST /v1/usage/report``.
         *
         *     App developer self-reports the actuals for a previously-minted
         *     payment. The delta is refunded to their balance via the ledger.
         */
        ReportUsageRequest: {
            /** Work Id */
            work_id: string;
            /** Actual Work Units */
            actual_work_units: number;
            /** Request Id */
            request_id?: string | null;
        };
        /**
         * RequestPasswordResetRequest
         * @description Inbound: ``POST /v1/auth/password-reset/request``.
         */
        RequestPasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * ResendVerificationRequest
         * @description Inbound: ``POST /v1/auth/resend-verification``.
         */
        ResendVerificationRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * RouteView
         * @description A single selected route — what `Select()` returns, web-flavored.
         */
        RouteView: {
            /** Worker Url */
            worker_url: string;
            /** Eth Address */
            eth_address: string;
            /** Capability */
            capability: string;
            /** Offering */
            offering: string;
            /** Price Per Work Unit Wei */
            price_per_work_unit_wei: string;
            /** Work Unit */
            work_unit: string;
            /** Units Per Price */
            units_per_price: number;
            /** Quote Id */
            quote_id: string;
        };
        /**
         * SignupRequest
         * @description Inbound: ``POST /v1/accounts/signup``.
         */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * SignupResponse
         * @description Outbound: ``POST /v1/accounts/signup`` success.
         */
        SignupResponse: {
            user: components["schemas"]["UserResponse"];
            /**
             * Verification Required
             * @default true
             */
            verification_required: boolean;
        };
        /**
         * TopupRequest
         * @description Admin-side topup body.
         */
        TopupRequest: {
            /** Amount Wei */
            amount_wei: number;
            /**
             * Kind
             * @default manual
             */
            kind: string;
        };
        /**
         * TopupView
         * @description Admin-side topup result.
         */
        TopupView: {
            /**
             * Topup Id
             * Format: uuid
             */
            topup_id: string;
            /** New Balance Wei */
            new_balance_wei: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UsageRecordView
         * @description The persisted, first-write-wins reconciliation row.
         */
        UsageRecordView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Payment Id
             * Format: uuid
             */
            payment_id: string;
            /** Actual Work Units */
            actual_work_units: number;
            /** Actual Cost Wei */
            actual_cost_wei: string;
            /** Request Id */
            request_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UsageReportResponse
         * @description Outbound: ``POST /v1/usage/report``.
         */
        UsageReportResponse: {
            usage: components["schemas"]["UsageRecordView"];
            /** Refunded Wei */
            refunded_wei: string;
            /** Payment Status */
            payment_status: string;
            /** New Balance Wei */
            new_balance_wei: string;
        };
        /**
         * UserResponse
         * @description Outbound: the public view of a user.
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Email Verified At */
            email_verified_at: string | null;
            /** Approved */
            approved: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerifyEmailRequest
         * @description Inbound: ``POST /v1/accounts/verify-email``.
         */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    signup_endpoint_v1_accounts_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_endpoint_v1_accounts_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_endpoint_v1_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_password_reset_endpoint_v1_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_password_reset_endpoint_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_endpoint_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_endpoint_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                open_clearinghouse_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_endpoint_v1_accounts_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                open_clearinghouse_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_providers_endpoint_v1_auth_oauth_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    oauth_login_endpoint_v1_auth_oauth__provider__login_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_callback_endpoint_v1_auth_oauth__provider__callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_endpoint_v1_accounts_me_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                open_clearinghouse_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_key_endpoint_v1_accounts_me_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                open_clearinghouse_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateApiKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_endpoint_v1_accounts_me_api_keys__api_key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                api_key_id: string;
            };
            cookie?: {
                open_clearinghouse_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_balance_v1_accounts_me_balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                open_clearinghouse_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_ledger_v1_accounts_me_ledger_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                open_clearinghouse_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_topup_user_v1_admin_users__user_id__topup_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopupView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_users_endpoint_v1_admin_users_pending_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingUserList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_users_endpoint_v1_admin_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_user_endpoint_v1_admin_users__user_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovedUserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_billing_config_endpoint_v1_admin_users__user_id__billing_config_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_billing_config_endpoint_v1_admin_users__user_id__billing_config_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillingConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deposit_snapshots_endpoint_v1_admin_deposit_snapshots_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepositSnapshotList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_entries_endpoint_v1_admin_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_endpoint_v1_admin_users__user_id__resend_verification_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_capabilities_endpoint_v1_admin_discovery_capabilities_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_orchestrators_endpoint_v1_admin_discovery_orchestrators_get: {
        parameters: {
            query?: {
                capability?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_capabilities_endpoint_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                open_clearinghouse_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orchestrators_endpoint_v1_orchestrators_get: {
        parameters: {
            query?: {
                capability?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                open_clearinghouse_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestratorList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_route_endpoint_v1_routes_get: {
        parameters: {
            query: {
                capability: string;
                offering: string;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                open_clearinghouse_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mint_payment_endpoint_v1_payments_mint_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MintPaymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MintPaymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_payments_v1_payments_me_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_payment_endpoint_v1_payments__work_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_usage_endpoint_v1_usage_report_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportUsageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
