# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from livepeer.payments.v1 import payee_admin_pb2 as livepeer_dot_payments_dot_v1_dot_payee__admin__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in livepeer/payments/v1/payee_admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PayeeAdminStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResetSession = channel.unary_unary(
                '/livepeer.payments.v1.PayeeAdmin/ResetSession',
                request_serializer=livepeer_dot_payments_dot_v1_dot_payee__admin__pb2.ResetSessionRequest.SerializeToString,
                response_deserializer=livepeer_dot_payments_dot_v1_dot_payee__admin__pb2.ResetSessionResponse.FromString,
                _registered_method=True)


class PayeeAdminServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ResetSession(self, request, context):
        """Reset the active GetTicketParams session keyed by the stable
        sender/recipient/capability/offering identity. The current open
        session is marked closed, its recipientRand nonce ledger is
        dropped, and the next GetTicketParams call mints a fresh work_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PayeeAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetSession,
                    request_deserializer=livepeer_dot_payments_dot_v1_dot_payee__admin__pb2.ResetSessionRequest.FromString,
                    response_serializer=livepeer_dot_payments_dot_v1_dot_payee__admin__pb2.ResetSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'livepeer.payments.v1.PayeeAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('livepeer.payments.v1.PayeeAdmin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PayeeAdmin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.payments.v1.PayeeAdmin/ResetSession',
            livepeer_dot_payments_dot_v1_dot_payee__admin__pb2.ResetSessionRequest.SerializeToString,
            livepeer_dot_payments_dot_v1_dot_payee__admin__pb2.ResetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
