# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livepeer/payments/v1/payee_admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'livepeer/payments/v1/payee_admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&livepeer/payments/v1/payee_admin.proto\x12\x14livepeer.payments.v1\"^\n\x13ResetSessionRequest\x12\x0e\n\x06sender\x18\x01 \x01(\x0c\x12\x11\n\trecipient\x18\x02 \x01(\x0c\x12\x12\n\ncapability\x18\x03 \x01(\t\x12\x10\n\x08offering\x18\x04 \x01(\t\":\n\x14ResetSessionResponse\x12\r\n\x05reset\x18\x01 \x01(\x08\x12\x13\n\x0bold_work_id\x18\x02 \x01(\t2s\n\nPayeeAdmin\x12\x65\n\x0cResetSession\x12).livepeer.payments.v1.ResetSessionRequest\x1a*.livepeer.payments.v1.ResetSessionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'livepeer.payments.v1.payee_admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESETSESSIONREQUEST']._serialized_start=64
  _globals['_RESETSESSIONREQUEST']._serialized_end=158
  _globals['_RESETSESSIONRESPONSE']._serialized_start=160
  _globals['_RESETSESSIONRESPONSE']._serialized_end=218
  _globals['_PAYEEADMIN']._serialized_start=220
  _globals['_PAYEEADMIN']._serialized_end=335
# @@protoc_insertion_point(module_scope)
