# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from livepeer.payments.v1 import payer_daemon_pb2 as livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2
from livepeer.payments.v1 import types_pb2 as livepeer_dot_payments_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in livepeer/payments/v1/payer_daemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PayerDaemonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePayment = channel.unary_unary(
                '/livepeer.payments.v1.PayerDaemon/CreatePayment',
                request_serializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.CreatePaymentRequest.SerializeToString,
                response_deserializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.CreatePaymentResponse.FromString,
                _registered_method=True)
        self.ReportPaymentResult = channel.unary_unary(
                '/livepeer.payments.v1.PayerDaemon/ReportPaymentResult',
                request_serializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.ReportPaymentResultRequest.SerializeToString,
                response_deserializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.ReportPaymentResultResponse.FromString,
                _registered_method=True)
        self.GetDepositInfo = channel.unary_unary(
                '/livepeer.payments.v1.PayerDaemon/GetDepositInfo',
                request_serializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetDepositInfoRequest.SerializeToString,
                response_deserializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetDepositInfoResponse.FromString,
                _registered_method=True)
        self.GetSessionDebits = channel.unary_unary(
                '/livepeer.payments.v1.PayerDaemon/GetSessionDebits',
                request_serializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetSessionDebitsRequest.SerializeToString,
                response_deserializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetSessionDebitsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/livepeer.payments.v1.PayerDaemon/Health',
                request_serializer=livepeer_dot_payments_dot_v1_dot_types__pb2.HealthRequest.SerializeToString,
                response_deserializer=livepeer_dot_payments_dot_v1_dot_types__pb2.HealthResponse.FromString,
                _registered_method=True)


class PayerDaemonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePayment(self, request, context):
        """Create a payment blob (a `Payment` carrying one or more tickets)
        for a selected payee identity against an accepted quote and funded
        budget.

        The caller provides:
        1. the accepted quote identity and unit pricing basis
        2. the funded value / budget for this request or session
        3. the selected broker URL for ticket-params retrieval

        Sender mode then:
        1. POSTs the request context to the broker's
        `/v1/payment/ticket-params` endpoint.
        2. Receives canonical `TicketParams` back.
        3. Validates the funding request against sender escrow / EV caps.
        4. Signs a `Payment` whose wire `expected_price` reflects the
        accepted quote basis.

        The funded value is the caller's authorized budget, not a mandatory
        winning-ticket size. The receiver may answer with a larger
        `TicketParams.face_value` plus a lower `TicketParams.win_prob` when
        redemption economics require a redeemable ticket. Senders MUST
        treat the returned `TicketParams` as the source of truth and not
        assume the returned winning-ticket face value equals the funded
        value they requested.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportPaymentResult(self, request, context):
        """Report the payee-side outcome for a previously-minted payment. The
        payer daemon uses this to invalidate cached session state when the
        payee reports a machine-readable rejection such as
        INVALID_RECIPIENT_RAND.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDepositInfo(self, request, context):
        """Inspect the payer's current TicketBroker deposit / reserve state.
        Read-only; the daemon does not fund escrow.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionDebits(self, request, context):
        """Deprecated: NOT the reconciliation source, and not implemented.

        The payer daemon keeps no debit ledger. Debits happen payee-side —
        the broker debits its payee daemon as usage is claimed — so a payer
        has nothing to report and this RPC returns UNIMPLEMENTED.

        Session usage is reconciled from the payee side instead:

        - the signed settlement record (`Livepeer-Settlement`), carrying
        cumulative claimed and debited units, the billed value, and the
        session's rotation chain; or
        - a direct read of `GET {worker_url}/v1/settlement/{id}` when the
        record should not cross a customer-controlled SDK at all.

        `debited_units` there is the authoritative billing quantity. Two
        ledgers is how two ledgers drift, so the payee's is the only one.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health returns "ok" if the daemon is ready to mint payments. The
        gateway calls this once at startup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PayerDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePayment,
                    request_deserializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.CreatePaymentRequest.FromString,
                    response_serializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.CreatePaymentResponse.SerializeToString,
            ),
            'ReportPaymentResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportPaymentResult,
                    request_deserializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.ReportPaymentResultRequest.FromString,
                    response_serializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.ReportPaymentResultResponse.SerializeToString,
            ),
            'GetDepositInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDepositInfo,
                    request_deserializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetDepositInfoRequest.FromString,
                    response_serializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetDepositInfoResponse.SerializeToString,
            ),
            'GetSessionDebits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionDebits,
                    request_deserializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetSessionDebitsRequest.FromString,
                    response_serializer=livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetSessionDebitsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=livepeer_dot_payments_dot_v1_dot_types__pb2.HealthRequest.FromString,
                    response_serializer=livepeer_dot_payments_dot_v1_dot_types__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'livepeer.payments.v1.PayerDaemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('livepeer.payments.v1.PayerDaemon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PayerDaemon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.payments.v1.PayerDaemon/CreatePayment',
            livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.CreatePaymentRequest.SerializeToString,
            livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.CreatePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportPaymentResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.payments.v1.PayerDaemon/ReportPaymentResult',
            livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.ReportPaymentResultRequest.SerializeToString,
            livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.ReportPaymentResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDepositInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.payments.v1.PayerDaemon/GetDepositInfo',
            livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetDepositInfoRequest.SerializeToString,
            livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetDepositInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionDebits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.payments.v1.PayerDaemon/GetSessionDebits',
            livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetSessionDebitsRequest.SerializeToString,
            livepeer_dot_payments_dot_v1_dot_payer__daemon__pb2.GetSessionDebitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.payments.v1.PayerDaemon/Health',
            livepeer_dot_payments_dot_v1_dot_types__pb2.HealthRequest.SerializeToString,
            livepeer_dot_payments_dot_v1_dot_types__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
