[package]
name = "streaming-ws-example"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "streaming-ws"
path = "src/main.rs"

[dependencies]
livepeer-open-clearinghouse-sdk = { path = "../../../sdks/rust" }
base64 = "0.22"
k256 = { version = "0.13", features = ["ecdsa"] }
rand_core = { version = "0.6", features = ["getrandom"] }
serde_json = "1.0"
sha3 = "0.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
