[package]
name = "streaming-ws-example"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "streaming-ws"
path = "src/main.rs"

[dependencies]
livepeer-open-clearinghouse-sdk = { path = "../../../sdks/rust" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
