// Package openclearinghouse provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openclearinghouse

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateJobRequestTransport.
const (
	CreateJobRequestTransportMultipart CreateJobRequestTransport = "multipart"
	CreateJobRequestTransportStream    CreateJobRequestTransport = "stream"
	CreateJobRequestTransportUnary     CreateJobRequestTransport = "unary"
)

// Valid indicates whether the value is a known member of the CreateJobRequestTransport enum.
func (e CreateJobRequestTransport) Valid() bool {
	switch e {
	case CreateJobRequestTransportMultipart:
		return true
	case CreateJobRequestTransportStream:
		return true
	case CreateJobRequestTransportUnary:
		return true
	default:
		return false
	}
}

// Defines values for CreateJobResponseTransport.
const (
	CreateJobResponseTransportMultipart CreateJobResponseTransport = "multipart"
	CreateJobResponseTransportStream    CreateJobResponseTransport = "stream"
	CreateJobResponseTransportUnary     CreateJobResponseTransport = "unary"
)

// Valid indicates whether the value is a known member of the CreateJobResponseTransport enum.
func (e CreateJobResponseTransport) Valid() bool {
	switch e {
	case CreateJobResponseTransportMultipart:
		return true
	case CreateJobResponseTransportStream:
		return true
	case CreateJobResponseTransportUnary:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusResponseAccountingOutcome.
const (
	BrokerSettled          JobStatusResponseAccountingOutcome = "broker_settled"
	ConservativeFullCharge JobStatusResponseAccountingOutcome = "conservative_full_charge"
	NonAdmissionAudit      JobStatusResponseAccountingOutcome = "non_admission_audit"
	Unresolved             JobStatusResponseAccountingOutcome = "unresolved"
)

// Valid indicates whether the value is a known member of the JobStatusResponseAccountingOutcome enum.
func (e JobStatusResponseAccountingOutcome) Valid() bool {
	switch e {
	case BrokerSettled:
		return true
	case ConservativeFullCharge:
		return true
	case NonAdmissionAudit:
		return true
	case Unresolved:
		return true
	default:
		return false
	}
}

// Defines values for RouteSnapshotProtocol.
const (
	PaidJobv1     RouteSnapshotProtocol = "paid-job/v1"
	PaidSessionv1 RouteSnapshotProtocol = "paid-session/v1"
)

// Valid indicates whether the value is a known member of the RouteSnapshotProtocol enum.
func (e RouteSnapshotProtocol) Valid() bool {
	switch e {
	case PaidJobv1:
		return true
	case PaidSessionv1:
		return true
	default:
		return false
	}
}

// Defines values for RouteSnapshotSchemaVersion.
const (
	RouteSnapshotv1 RouteSnapshotSchemaVersion = "route-snapshot/v1"
)

// Valid indicates whether the value is a known member of the RouteSnapshotSchemaVersion enum.
func (e RouteSnapshotSchemaVersion) Valid() bool {
	switch e {
	case RouteSnapshotv1:
		return true
	default:
		return false
	}
}

// Defines values for SessionAxesAttachment.
const (
	SessionAxesAttachmentExternal SessionAxesAttachment = "external"
)

// Valid indicates whether the value is a known member of the SessionAxesAttachment enum.
func (e SessionAxesAttachment) Valid() bool {
	switch e {
	case SessionAxesAttachmentExternal:
		return true
	default:
		return false
	}
}

// Defines values for SessionAxesMetering.
const (
	SessionAxesMeteringRunnerReported SessionAxesMetering = "runner-reported"
)

// Valid indicates whether the value is a known member of the SessionAxesMetering enum.
func (e SessionAxesMetering) Valid() bool {
	switch e {
	case SessionAxesMeteringRunnerReported:
		return true
	default:
		return false
	}
}

// Defines values for SessionAxesRefill.
const (
	SessionAxesRefillBounded    SessionAxesRefill = "bounded"
	SessionAxesRefillExtensible SessionAxesRefill = "extensible"
)

// Valid indicates whether the value is a known member of the SessionAxesRefill enum.
func (e SessionAxesRefill) Valid() bool {
	switch e {
	case SessionAxesRefillBounded:
		return true
	case SessionAxesRefillExtensible:
		return true
	default:
		return false
	}
}

// Defines values for SessionAxesViewAttachment.
const (
	SessionAxesViewAttachmentExternal SessionAxesViewAttachment = "external"
)

// Valid indicates whether the value is a known member of the SessionAxesViewAttachment enum.
func (e SessionAxesViewAttachment) Valid() bool {
	switch e {
	case SessionAxesViewAttachmentExternal:
		return true
	default:
		return false
	}
}

// Defines values for SessionAxesViewMetering.
const (
	SessionAxesViewMeteringRunnerReported SessionAxesViewMetering = "runner-reported"
)

// Valid indicates whether the value is a known member of the SessionAxesViewMetering enum.
func (e SessionAxesViewMetering) Valid() bool {
	switch e {
	case SessionAxesViewMeteringRunnerReported:
		return true
	default:
		return false
	}
}

// Defines values for SessionAxesViewRefill.
const (
	SessionAxesViewRefillBounded    SessionAxesViewRefill = "bounded"
	SessionAxesViewRefillExtensible SessionAxesViewRefill = "extensible"
)

// Valid indicates whether the value is a known member of the SessionAxesViewRefill enum.
func (e SessionAxesViewRefill) Valid() bool {
	switch e {
	case SessionAxesViewRefillBounded:
		return true
	case SessionAxesViewRefillExtensible:
		return true
	default:
		return false
	}
}

// Defines values for SessionSettlementSignatureAlgorithm.
const (
	SessionSettlementSignatureAlgorithmSecp256k1 SessionSettlementSignatureAlgorithm = "secp256k1"
)

// Valid indicates whether the value is a known member of the SessionSettlementSignatureAlgorithm enum.
func (e SessionSettlementSignatureAlgorithm) Valid() bool {
	switch e {
	case SessionSettlementSignatureAlgorithmSecp256k1:
		return true
	default:
		return false
	}
}

// Defines values for SessionSettlementSignatureCanonicalization.
const (
	SessionSettlementSignatureCanonicalizationJcs SessionSettlementSignatureCanonicalization = "jcs"
)

// Valid indicates whether the value is a known member of the SessionSettlementSignatureCanonicalization enum.
func (e SessionSettlementSignatureCanonicalization) Valid() bool {
	switch e {
	case SessionSettlementSignatureCanonicalizationJcs:
		return true
	default:
		return false
	}
}

// Defines values for SettlementSignatureAlgorithm.
const (
	SettlementSignatureAlgorithmSecp256k1 SettlementSignatureAlgorithm = "secp256k1"
)

// Valid indicates whether the value is a known member of the SettlementSignatureAlgorithm enum.
func (e SettlementSignatureAlgorithm) Valid() bool {
	switch e {
	case SettlementSignatureAlgorithmSecp256k1:
		return true
	default:
		return false
	}
}

// Defines values for SettlementSignatureCanonicalization.
const (
	SettlementSignatureCanonicalizationJcs SettlementSignatureCanonicalization = "jcs"
)

// Valid indicates whether the value is a known member of the SettlementSignatureCanonicalization enum.
func (e SettlementSignatureCanonicalization) Valid() bool {
	switch e {
	case SettlementSignatureCanonicalizationJcs:
		return true
	default:
		return false
	}
}

// Defines values for QueryEventsEndpointV1TelemetryEventsGetParamsFormat.
const (
	Json   QueryEventsEndpointV1TelemetryEventsGetParamsFormat = "json"
	Ndjson QueryEventsEndpointV1TelemetryEventsGetParamsFormat = "ndjson"
)

// Valid indicates whether the value is a known member of the QueryEventsEndpointV1TelemetryEventsGetParamsFormat enum.
func (e QueryEventsEndpointV1TelemetryEventsGetParamsFormat) Valid() bool {
	switch e {
	case Json:
		return true
	case Ndjson:
		return true
	default:
		return false
	}
}

// AdminUserList defines model for AdminUserList.
type AdminUserList struct {
	Items []AdminUserView `json:"items"`
	Total int             `json:"total"`
}

// AdminUserView Admin listing row: identity + approval + balance, no secrets.
type AdminUserView struct {
	Approved        bool               `json:"approved"`
	BalanceWei      int                `json:"balance_wei"`
	CreatedAt       time.Time          `json:"created_at"`
	Email           string             `json:"email"`
	EmailVerifiedAt *time.Time         `json:"email_verified_at"`
	Id              openapi_types.UUID `json:"id"`
}

// ApiKeyList Outbound: list of a user's keys.
type ApiKeyList struct {
	Items []ApiKeyView `json:"items"`
}

// ApiKeyView The non-secret view of a key.
type ApiKeyView struct {
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	Label      string             `json:"label"`
	LastUsedAt *time.Time         `json:"last_used_at"`
	Prefix     string             `json:"prefix"`
	RevokedAt  *time.Time         `json:"revoked_at"`
}

// ApprovedUserView A user with an active approval.
type ApprovedUserView struct {
	ApprovedAt time.Time          `json:"approved_at"`
	OperatorId openapi_types.UUID `json:"operator_id"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// AuditEntryList defines model for AuditEntryList.
type AuditEntryList struct {
	Items []AuditEntryView `json:"items"`
}

// AuditEntryView One row of operator_audit, joined with the operator + target emails.
type AuditEntryView struct {
	Action          string                  `json:"action"`
	CreatedAt       time.Time               `json:"created_at"`
	Id              openapi_types.UUID      `json:"id"`
	OperatorEmail   string                  `json:"operator_email"`
	Params          *map[string]interface{} `json:"params"`
	TargetUserEmail *string                 `json:"target_user_email"`
	TargetUserId    *openapi_types.UUID     `json:"target_user_id"`
}

// BalanceView The user-facing snapshot of credit state.
type BalanceView struct {
	AmountWei string             `json:"amount_wei"`
	UpdatedAt time.Time          `json:"updated_at"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// BillingConfigResponse Outbound: per-user config plus the effective values.
type BillingConfigResponse struct {
	// Config Per-user billing config (null = inherit default).
	Config BillingConfigView `json:"config"`

	// Effective The values that would be applied right now (overrides + defaults).
	Effective EffectiveBillingConfigView `json:"effective"`
}

// BillingConfigUpdate Inbound: “PUT /v1/admin/users/{id}/billing-config“.
//
// Send `null` to clear an override and inherit the default; send an
// integer to set/replace it.
type BillingConfigUpdate struct {
	AutoReplenishIncrementWei *int `json:"auto_replenish_increment_wei,omitempty"`
	AutoReplenishThresholdWei *int `json:"auto_replenish_threshold_wei,omitempty"`
	SpendPeriodCapWei         *int `json:"spend_period_cap_wei,omitempty"`
	SpendPeriodSeconds        *int `json:"spend_period_seconds,omitempty"`
}

// BillingConfigView Per-user billing config (null = inherit default).
type BillingConfigView struct {
	AutoReplenishIncrementWei *int               `json:"auto_replenish_increment_wei"`
	AutoReplenishThresholdWei *int               `json:"auto_replenish_threshold_wei"`
	SpendPeriodCapWei         *int               `json:"spend_period_cap_wei"`
	SpendPeriodSeconds        *int               `json:"spend_period_seconds"`
	UserId                    openapi_types.UUID `json:"user_id"`
}

// CapStatus Cap headroom snapshot returned with every successful refill.
//
// All percentages are in “[0.0, 1.0]“. “None“ means the cap
// isn't enabled / configured (e.g., user has no spend-period cap
// set, or operator-pool cap is opt-in and disabled).
//
// “will_refuse_next_refill“ flips “true“ when any enabled cap
// is at or above the imminent-refusal threshold AND the projected
// next-mint would push it over. SDK uses this to surface a
// winddown warning to the customer one refill window early.
//
// “winddown_reason“ is a short machine-readable string when
// “will_refuse_next_refill=true“: “"session_cap_imminent"“,
// “"spend_period_cap_imminent"“, “"user_balance_imminent"“,
// “"operator_pool_cap_imminent"“. “None“ otherwise.
type CapStatus struct {
	OperatorPoolPctUsed  *float32 `json:"operator_pool_pct_used,omitempty"`
	SessionPctUsed       float32  `json:"session_pct_used"`
	SpendPeriodPctUsed   *float32 `json:"spend_period_pct_used,omitempty"`
	UserBalancePctUsed   *float32 `json:"user_balance_pct_used,omitempty"`
	WillRefuseNextRefill bool     `json:"will_refuse_next_refill"`
	WinddownReason       *string  `json:"winddown_reason,omitempty"`
}

// CapabilityList defines model for CapabilityList.
type CapabilityList struct {
	Items []CapabilityView `json:"items"`
}

// CapabilityView defines model for CapabilityView.
type CapabilityView struct {
	Name              string             `json:"name"`
	Offerings         []OfferingView     `json:"offerings"`
	WorkUnit          *string            `json:"work_unit"`
	WorkUnitEstimator *WorkUnitEstimator `json:"work_unit_estimator"`
}

// CloseSessionRequest Inbound: “POST /v1/sessions/{id}/close“.
//
// SDK forwards the required broker-signed terminal settlement. The
// reported units and optional outcome are consistency assertions;
// signed settlement fields are authoritative for accounting.
type CloseSessionRequest struct {
	ActualUnits int                       `json:"actual_units"`
	Outcome     *string                   `json:"outcome,omitempty"`
	Settlement  SessionSettlementEnvelope `json:"settlement"`
}

// CloseSessionResponse Outbound: “POST /v1/sessions/{id}/close“.
//
// Carries the final accounting: how much the customer was billed
// for the session, how much encumbered value is being refunded
// back to their balance, and the settlement outcome string.
type CloseSessionResponse struct {
	ActualUnits    int                `json:"actual_units"`
	BilledValueWei int                `json:"billed_value_wei"`
	ClosedAt       time.Time          `json:"closed_at"`
	Outcome        string             `json:"outcome"`
	RefundWei      int                `json:"refund_wei"`
	SessionId      openapi_types.UUID `json:"session_id"`
	WorkId         string             `json:"work_id"`
}

// ConfirmPasswordResetRequest Inbound: “POST /v1/auth/password-reset/confirm“.
type ConfirmPasswordResetRequest struct {
	NewPassword string `json:"new_password"`
	Token       string `json:"token"`
}

// CreateApiKeyRequest Inbound: “POST /v1/accounts/me/api-keys“.
type CreateApiKeyRequest struct {
	Label string `json:"label"`
}

// CreateApiKeyResponse Outbound: includes the raw key one time only.
type CreateApiKeyResponse struct {
	// Key The non-secret view of a key.
	Key ApiKeyView `json:"key"`

	// RawKey Shown only at creation; Livepeer Open Clearinghouse cannot recover it later
	RawKey string `json:"raw_key"`
}

// CreateJobRequest Inbound: “POST /v1/jobs“.
//
// SDK declares its intent for an atomic / post-settled / streaming
// job. “max_total_units“ is the worst-case ceiling LOC encumbers
// up front; if omitted, defaults to “estimated_units“ (the SDK is
// asserting "I know exactly what I need" — typical for case (a)).
//
// For case (b)/(c) workloads where output_tokens are unknown,
// customers should pass a generous “max_total_units“ to give the
// broker room. Refunds happen at “/settle“.
type CreateJobRequest struct {
	Capability     string                    `json:"capability"`
	EstimatedUnits int                       `json:"estimated_units"`
	MaxTotalUnits  *int                      `json:"max_total_units,omitempty"`
	Offering       string                    `json:"offering"`
	RouteBinding   *RouteBinding             `json:"route_binding,omitempty"`
	Transport      CreateJobRequestTransport `json:"transport"`
}

// CreateJobRequestTransport defines model for CreateJobRequest.Transport.
type CreateJobRequestTransport string

// CreateJobResponse Outbound: “POST /v1/jobs“.
//
// Carries the broker target + minted envelope so the SDK can issue
// its one-shot call to the broker directly (handoff mode). The
// “settle_endpoint“ is the LOC URL the SDK posts to after reading
// the broker's response (terminal headers for unary/multipart, or a
// terminal settlement lookup when stream trailers are inaccessible).
type CreateJobResponse struct {
	BrokerUrl        string             `json:"broker_url"`
	ExpectedValueWei int                `json:"expected_value_wei"`
	FundedValueWei   int                `json:"funded_value_wei"`
	JobId            openapi_types.UUID `json:"job_id"`
	OpenedAt         time.Time          `json:"opened_at"`
	PaymentEnvelope  string             `json:"payment_envelope"`
	Protocol         string             `json:"protocol"`
	RequestId        string             `json:"request_id"`

	// RouteSnapshot Immutable public route declaration used to authorize one open.
	RouteSnapshot  RouteSnapshot              `json:"route_snapshot"`
	SettleEndpoint string                     `json:"settle_endpoint"`
	Transport      CreateJobResponseTransport `json:"transport"`
	WorkId         string                     `json:"work_id"`
	WorkUnit       string                     `json:"work_unit"`
}

// CreateJobResponseTransport defines model for CreateJobResponse.Transport.
type CreateJobResponseTransport string

// CreateOperatorRequest Inbound: “POST /v1/admin/operators“.
type CreateOperatorRequest struct {
	Email openapi_types.Email `json:"email"`
	Name  string              `json:"name"`
	Role  *string             `json:"role,omitempty"`
}

// CreateSdkApprovalRequest Inbound: “POST /v1/admin/sdk-approvals“.
type CreateSdkApprovalRequest struct {
	GitSha7 string  `json:"git_sha7"`
	Lang    string  `json:"lang"`
	Notes   *string `json:"notes,omitempty"`
	Status  *string `json:"status,omitempty"`
	Version string  `json:"version"`
}

// CreateSessionRequest Inbound: “POST /v1/sessions“.
//
// The SDK declares its intent for a long-lived session: the
// capability + offering pair to bill against, the estimated runway
// (best-guess of what the session is likely to consume), and the
// absolute ceiling (“max_total_units“) that LOC will encumber up
// front under handoff-mode's worst-case sizing rule.
//
// “max_total_units“ MUST be >= “estimated_runway_units“ and > 0.
type CreateSessionRequest struct {
	Capability           string                  `json:"capability"`
	DescriptorSchema     string                  `json:"descriptor_schema"`
	EstimatedRunwayUnits int                     `json:"estimated_runway_units"`
	MaxTotalUnits        int                     `json:"max_total_units"`
	Offering             string                  `json:"offering"`
	RouteBinding         *RouteBinding           `json:"route_binding,omitempty"`
	SessionParams        *map[string]interface{} `json:"session_params,omitempty"`
}

// CreateSessionResponse Outbound: “POST /v1/sessions“.
//
// Carries everything the SDK needs to open the broker-side session
// and bookkeep the LOC-side lifecycle. The “payment_envelope“
// is base64-encoded wire-format Payment bytes — the SDK attaches
// it as the “Livepeer-Payment“ HTTP header when opening the broker's
// paid-session/v1 control resource.
//
// Per exec-plan 002 handoff design, LOC never sits in the data
// path: “broker_url“ is the orchestrator's HTTP/WS endpoint the
// SDK talks to directly. The two “*_endpoint“ fields are
// LOC-relative paths the SDK calls when it needs to refill or
// explicitly close the session.
type CreateSessionResponse struct {
	BrokerUrl        string    `json:"broker_url"`
	CloseEndpoint    string    `json:"close_endpoint"`
	ExpectedValueWei int       `json:"expected_value_wei"`
	FundedValueWei   int       `json:"funded_value_wei"`
	OpenedAt         time.Time `json:"opened_at"`
	PaymentEnvelope  string    `json:"payment_envelope"`
	Protocol         string    `json:"protocol"`
	RefillEndpoint   string    `json:"refill_endpoint"`
	RequestId        string    `json:"request_id"`

	// RouteSnapshot Immutable public route declaration used to authorize one open.
	RouteSnapshot RouteSnapshot `json:"route_snapshot"`

	// Session Authoritative paid-session/v1 offering axes selected for the session.
	Session   SessionAxesView    `json:"session"`
	SessionId openapi_types.UUID `json:"session_id"`
	WorkId    string             `json:"work_id"`
}

// DepositSnapshotList defines model for DepositSnapshotList.
type DepositSnapshotList struct {
	Items []DepositSnapshotView `json:"items"`
}

// DepositSnapshotView One row from the periodic payment-daemon deposit poll.
type DepositSnapshotView struct {
	CurrentRound                   *int               `json:"current_round"`
	DepositWei                     int                `json:"deposit_wei"`
	Id                             openapi_types.UUID `json:"id"`
	ReserveWei                     int                `json:"reserve_wei"`
	TakenAt                        time.Time          `json:"taken_at"`
	TicketValidityPeriod           *int               `json:"ticket_validity_period"`
	TicketValidityPeriodObservedAt *time.Time         `json:"ticket_validity_period_observed_at"`
	WithdrawRound                  int                `json:"withdraw_round"`
}

// EffectiveBillingConfigView The values that would be applied right now (overrides + defaults).
type EffectiveBillingConfigView struct {
	AutoReplenishIncrementWei int `json:"auto_replenish_increment_wei"`
	AutoReplenishThresholdWei int `json:"auto_replenish_threshold_wei"`
	SpendPeriodCapWei         int `json:"spend_period_cap_wei"`
	SpendPeriodSeconds        int `json:"spend_period_seconds"`
}

// EmailEventList defines model for EmailEventList.
type EmailEventList struct {
	Items []EmailEventView `json:"items"`
}

// EmailEventView Outbound: one row from `GET /v1/admin/email/events`.
type EmailEventView struct {
	EmailSendId       *openapi_types.UUID `json:"email_send_id"`
	EventType         string              `json:"event_type"`
	Id                openapi_types.UUID  `json:"id"`
	ProviderEventId   string              `json:"provider_event_id"`
	ProviderMessageId *string             `json:"provider_message_id"`
	ReceivedAt        time.Time           `json:"received_at"`
	ToAddress         *string             `json:"to_address"`
}

// EventList Outbound: “GET /v1/telemetry/events?format=json“ response.
//
// “next_cursor“ is “None“ when the page exhausts the result set.
type EventList struct {
	Items      []EventView `json:"items"`
	NextCursor *string     `json:"next_cursor,omitempty"`
}

// EventView One row of telemetry_event as the customer sees it.
//
// The four enrichment columns (geo_region, account_tier,
// broker_operator_id, ingest_node_id) are deliberately NOT exposed —
// they're operator-only context.
type EventView struct {
	ClientTs           *time.Time             `json:"client_ts"`
	CorrelationId      *openapi_types.UUID    `json:"correlation_id"`
	EventSchemaVersion int                    `json:"event_schema_version"`
	EventType          string                 `json:"event_type"`
	Id                 openapi_types.UUID     `json:"id"`
	Payload            map[string]interface{} `json:"payload"`
	ReceivedTs         time.Time              `json:"received_ts"`
	Source             string                 `json:"source"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// IngestEventIn One inbound event in a batch.
type IngestEventIn struct {
	ClientTs           *time.Time              `json:"client_ts,omitempty"`
	CorrelationId      *openapi_types.UUID     `json:"correlation_id,omitempty"`
	EventSchemaVersion int                     `json:"event_schema_version"`
	EventType          string                  `json:"event_type"`
	Payload            *map[string]interface{} `json:"payload,omitempty"`
}

// IngestRequest Inbound: “POST /v1/telemetry“. A batch of events from one SDK
// process.
type IngestRequest struct {
	Events []IngestEventIn `json:"events"`
}

// IngestResponse Outbound: “POST /v1/telemetry“ 202 response.
type IngestResponse struct {
	Accepted   int       `json:"accepted"`
	Rejected   *int      `json:"rejected,omitempty"`
	Rejections *[]string `json:"rejections,omitempty"`
}

// JobAxes Known paid-job/v1 axes, preserving future minor-version additions.
type JobAxes struct {
	Transports           []string               `json:"transports"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// JobStatusResponse Customer-visible job state without conflating billing evidence.
type JobStatusResponse struct {
	AccountingOutcome                     JobStatusResponseAccountingOutcome `json:"accounting_outcome"`
	ActualUnits                           *int                               `json:"actual_units"`
	BilledValueWei                        *int                               `json:"billed_value_wei"`
	BrokerExchangeOutcome                 *string                            `json:"broker_exchange_outcome"`
	ClosedAt                              *time.Time                         `json:"closed_at"`
	CreationRound                         *int                               `json:"creation_round"`
	CurrentTicketValidityPeriod           *int                               `json:"current_ticket_validity_period"`
	CurrentTicketValidityPeriodObservedAt *time.Time                         `json:"current_ticket_validity_period_observed_at"`
	ExpiresAfterRound                     *int                               `json:"expires_after_round"`
	FundedValueWei                        int                                `json:"funded_value_wei"`
	JobId                                 openapi_types.UUID                 `json:"job_id"`
	MintTicketValidityPeriod              *int                               `json:"mint_ticket_validity_period"`
	MintTicketValidityPeriodObservedAt    *time.Time                         `json:"mint_ticket_validity_period_observed_at"`
	ObservedCurrentRound                  *int                               `json:"observed_current_round"`
	OpenedAt                              time.Time                          `json:"opened_at"`
	RequestId                             string                             `json:"request_id"`
	State                                 string                             `json:"state"`
	WorkId                                string                             `json:"work_id"`
}

// JobStatusResponseAccountingOutcome defines model for JobStatusResponse.AccountingOutcome.
type JobStatusResponseAccountingOutcome string

// LedgerEntryView One row of the credit ledger (audit history).
type LedgerEntryView struct {
	CreatedAt        time.Time           `json:"created_at"`
	DeltaWei         string              `json:"delta_wei"`
	Id               openapi_types.UUID  `json:"id"`
	Reason           string              `json:"reason"`
	RelatedPaymentId *openapi_types.UUID `json:"related_payment_id"`
	RelatedTopupId   *openapi_types.UUID `json:"related_topup_id"`
}

// LedgerPage defines model for LedgerPage.
type LedgerPage struct {
	Items []LedgerEntryView `json:"items"`
}

// LoginRequest Inbound: “POST /v1/auth/login“.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse Outbound: “POST /v1/auth/login“ success.
//
// The session token is delivered via cookie; the body just confirms.
type LoginResponse struct {
	// User Outbound: the public view of a user.
	User UserResponse `json:"user"`
}

// NotificationPrefView One cell of the (trigger x channel) matrix as the portal renders it.
type NotificationPrefView struct {
	Channel   string `json:"channel"`
	Enabled   bool   `json:"enabled"`
	IsDefault bool   `json:"is_default"`
	Trigger   string `json:"trigger"`
}

// NotificationPrefsResponse Full resolved-preferences matrix for the calling user.
type NotificationPrefsResponse struct {
	Items []NotificationPrefView `json:"items"`
}

// OfferingView defines model for OfferingView.
type OfferingView struct {
	Extra               *map[string]interface{} `json:"extra,omitempty"`
	Id                  string                  `json:"id"`
	Job                 *JobAxes                `json:"job"`
	PricePerWorkUnitWei *string                 `json:"price_per_work_unit_wei"`
	Protocol            string                  `json:"protocol"`
	Session             *SessionAxes            `json:"session"`

	// UnitsPerPrice Canonical decimal encoding of an unsigned 64-bit integer.
	UnitsPerPrice     string             `json:"units_per_price"`
	WorkUnit          *string            `json:"work_unit"`
	WorkUnitEstimator *WorkUnitEstimator `json:"work_unit_estimator"`
}

// OperatorList defines model for OperatorList.
type OperatorList struct {
	Items []OperatorView `json:"items"`
}

// OperatorView Public-facing operator shape (no token material).
type OperatorView struct {
	CreatedAt   time.Time          `json:"created_at"`
	Email       string             `json:"email"`
	Id          openapi_types.UUID `json:"id"`
	LastLoginAt *time.Time         `json:"last_login_at"`
	Name        string             `json:"name"`
	RevokedAt   *time.Time         `json:"revoked_at"`
	Role        string             `json:"role"`
}

// OperatorWithToken Outbound from create + rotate-token. The “raw_token“ field is
// shown exactly once; the gateway only stores its hash.
type OperatorWithToken struct {
	// Operator Public-facing operator shape (no token material).
	Operator OperatorView `json:"operator"`
	RawToken string       `json:"raw_token"`
}

// OrchestratorList defines model for OrchestratorList.
type OrchestratorList struct {
	Items []OrchestratorView `json:"items"`
}

// OrchestratorView defines model for OrchestratorView.
type OrchestratorView struct {
	Capabilities    []CapabilityView `json:"capabilities"`
	EthAddress      string           `json:"eth_address"`
	FreshnessStatus string           `json:"freshness_status"`
	SignatureStatus string           `json:"signature_status"`
	WorkerUrl       string           `json:"worker_url"`
}

// PaymentList defines model for PaymentList.
type PaymentList struct {
	Items []PaymentView `json:"items"`
}

// PaymentView Outbound: a single payment row in user-facing JSON.
type PaymentView struct {
	Capability          string             `json:"capability"`
	CreatedAt           time.Time          `json:"created_at"`
	ExpectedValueWei    string             `json:"expected_value_wei"`
	FundedValueWei      string             `json:"funded_value_wei"`
	Id                  openapi_types.UUID `json:"id"`
	Offering            string             `json:"offering"`
	RecipientEthAddress string             `json:"recipient_eth_address"`
	RefundedWei         string             `json:"refunded_wei"`
	ReservedWei         string             `json:"reserved_wei"`
	Status              string             `json:"status"`
	UpdatedAt           time.Time          `json:"updated_at"`
	WorkId              string             `json:"work_id"`
	WorkUnitsRequested  int                `json:"work_units_requested"`
}

// PendingUserList defines model for PendingUserList.
type PendingUserList struct {
	Items []PendingUserView `json:"items"`
}

// PendingUserView A user not yet approved.
type PendingUserView struct {
	CreatedAt       time.Time          `json:"created_at"`
	Email           string             `json:"email"`
	EmailVerifiedAt *time.Time         `json:"email_verified_at"`
	Id              openapi_types.UUID `json:"id"`
}

// PortalNotificationList defines model for PortalNotificationList.
type PortalNotificationList struct {
	Items []PortalNotificationView `json:"items"`
}

// PortalNotificationView One row of the in-portal banner feed.
type PortalNotificationView struct {
	Body        map[string]interface{} `json:"body"`
	DismissedAt *time.Time             `json:"dismissed_at"`
	FiredAt     time.Time              `json:"fired_at"`
	Id          openapi_types.UUID     `json:"id"`
	Trigger     string                 `json:"trigger"`
}

// RefillSessionRequest Inbound: “POST /v1/sessions/{id}/refill“.
//
// Body is mostly empty in v1 — the SDK signals "broker emitted
// Livepeer-Balance-Low, please mint more." The optional
// “observed_consumed_units“ is an advisory hint from the SDK's
// view of broker progress. Signed broker settlements, supplied on
// close/reconciliation, are authoritative for delivered work.
type RefillSessionRequest struct {
	ObservedConsumedUnits *int    `json:"observed_consumed_units,omitempty"`
	RebindFrom            *string `json:"rebind_from,omitempty"`
	ReplacesRequestId     *string `json:"replaces_request_id,omitempty"`
}

// RefillSessionResponse Outbound: “POST /v1/sessions/{id}/refill“ success (200).
//
// Carries the newly-minted top-up envelope plus a fresh cap_status
// snapshot. The SDK delivers “payment_envelope“ through the authoritative
// paid-session HTTP top-up URL; a control WebSocket is only an optional push
// mirror.
type RefillSessionResponse struct {
	// CapStatus Cap headroom snapshot returned with every successful refill.
	//
	// All percentages are in ``[0.0, 1.0]``. ``None`` means the cap
	// isn't enabled / configured (e.g., user has no spend-period cap
	// set, or operator-pool cap is opt-in and disabled).
	//
	// ``will_refuse_next_refill`` flips ``true`` when any enabled cap
	// is at or above the imminent-refusal threshold AND the projected
	// next-mint would push it over. SDK uses this to surface a
	// winddown warning to the customer one refill window early.
	//
	// ``winddown_reason`` is a short machine-readable string when
	// ``will_refuse_next_refill=true``: ``"session_cap_imminent"``,
	// ``"spend_period_cap_imminent"``, ``"user_balance_imminent"``,
	// ``"operator_pool_cap_imminent"``. ``None`` otherwise.
	CapStatus        CapStatus `json:"cap_status"`
	ExpectedValueWei int       `json:"expected_value_wei"`
	FundedValueWei   int       `json:"funded_value_wei"`
	PaymentEnvelope  string    `json:"payment_envelope"`
	RebindFrom       *string   `json:"rebind_from,omitempty"`
	RefillSeq        int       `json:"refill_seq"`
	RequestId        string    `json:"request_id"`
	WorkId           string    `json:"work_id"`
}

// RequestPasswordResetRequest Inbound: “POST /v1/auth/password-reset/request“.
type RequestPasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// ResendVerificationRequest Inbound: “POST /v1/auth/resend-verification“.
type ResendVerificationRequest struct {
	Email openapi_types.Email `json:"email"`
}

// RouteBinding Compact caller-stable identity for one signed selected route.
type RouteBinding struct {
	ConstraintFingerprint string `json:"constraint_fingerprint"`
	QuoteId               string `json:"quote_id"`

	// QuoteVersion Canonical decimal encoding of an unsigned 64-bit integer.
	QuoteVersion     string `json:"quote_version"`
	RouteFingerprint string `json:"route_fingerprint"`
}

// RouteSnapshot Immutable public route declaration used to authorize one open.
type RouteSnapshot struct {
	BrokerUrl             string                  `json:"broker_url"`
	Capability            string                  `json:"capability"`
	ConstraintFingerprint string                  `json:"constraint_fingerprint"`
	EthAddress            string                  `json:"eth_address"`
	Extra                 *map[string]interface{} `json:"extra,omitempty"`
	Job                   *JobAxes                `json:"job,omitempty"`
	Offering              string                  `json:"offering"`
	PricePerWorkUnitWei   string                  `json:"price_per_work_unit_wei"`
	Protocol              RouteSnapshotProtocol   `json:"protocol"`
	QuoteId               string                  `json:"quote_id"`

	// QuoteVersion Canonical decimal encoding of an unsigned 64-bit integer.
	QuoteVersion     string                      `json:"quote_version"`
	RouteFingerprint string                      `json:"route_fingerprint"`
	SchemaVersion    *RouteSnapshotSchemaVersion `json:"schema_version,omitempty"`
	Session          *SessionAxes                `json:"session,omitempty"`
	SettlementKeys   []SettlementKey             `json:"settlement_keys"`

	// UnitsPerPrice Canonical decimal encoding of an unsigned 64-bit integer.
	UnitsPerPrice     string             `json:"units_per_price"`
	WorkUnit          string             `json:"work_unit"`
	WorkUnitEstimator *WorkUnitEstimator `json:"work_unit_estimator,omitempty"`
}

// RouteSnapshotProtocol defines model for RouteSnapshot.Protocol.
type RouteSnapshotProtocol string

// RouteSnapshotSchemaVersion defines model for RouteSnapshot.SchemaVersion.
type RouteSnapshotSchemaVersion string

// RouteView A single selected route — what `Select()` returns, web-flavored.
type RouteView struct {
	Capability            string                  `json:"capability"`
	ConstraintFingerprint string                  `json:"constraint_fingerprint"`
	EthAddress            string                  `json:"eth_address"`
	Extra                 *map[string]interface{} `json:"extra,omitempty"`
	Job                   *JobAxes                `json:"job"`
	Offering              string                  `json:"offering"`
	PricePerWorkUnitWei   string                  `json:"price_per_work_unit_wei"`
	Protocol              string                  `json:"protocol"`
	QuoteId               string                  `json:"quote_id"`

	// QuoteVersion Canonical decimal encoding of an unsigned 64-bit integer.
	QuoteVersion string `json:"quote_version"`

	// RouteBinding Compact caller-stable identity for one signed selected route.
	RouteBinding     RouteBinding `json:"route_binding"`
	RouteFingerprint string       `json:"route_fingerprint"`

	// RouteSnapshot Immutable public route declaration used to authorize one open.
	RouteSnapshot  RouteSnapshot   `json:"route_snapshot"`
	Session        *SessionAxes    `json:"session"`
	SettlementKeys []SettlementKey `json:"settlement_keys"`

	// UnitsPerPrice Canonical decimal encoding of an unsigned 64-bit integer.
	UnitsPerPrice     string             `json:"units_per_price"`
	WorkUnit          string             `json:"work_unit"`
	WorkUnitEstimator *WorkUnitEstimator `json:"work_unit_estimator"`
	WorkerUrl         string             `json:"worker_url"`
}

// SdkApprovalList defines model for SdkApprovalList.
type SdkApprovalList struct {
	Items []SdkApprovalView `json:"items"`
}

// SdkApprovalView One row of sdk_approval — operator view.
type SdkApprovalView struct {
	AddedByOperatorId *openapi_types.UUID `json:"added_by_operator_id"`
	CreatedAt         time.Time           `json:"created_at"`
	GitSha7           string              `json:"git_sha7"`
	Id                openapi_types.UUID  `json:"id"`
	Lang              string              `json:"lang"`
	Notes             *string             `json:"notes"`
	Status            string              `json:"status"`
	UpdatedAt         time.Time           `json:"updated_at"`
	Version           string              `json:"version"`
}

// SdkDistributionEntry defines model for SdkDistributionEntry.
type SdkDistributionEntry struct {
	Count       int    `json:"count"`
	SdkIdentity string `json:"sdk_identity"`
	Status      string `json:"status"`
}

// SdkDistributionResponse defines model for SdkDistributionResponse.
type SdkDistributionResponse struct {
	Items []SdkDistributionEntry `json:"items"`
}

// SdkManifest Public payload at “GET /v1/sdk/manifest“.
//
// When the operator has configured a signing key, the response also
// carries “signature“ (Ed25519 over the canonical JSON of
// “{items, generated_at}“) and “key_fingerprint“ (first 16 hex
// of SHA-256 of the public key). SDKs verify by fetching the
// public key at “/v1/sdk/manifest/pubkey“ and recomputing.
type SdkManifest struct {
	GeneratedAt    time.Time          `json:"generated_at"`
	Items          []SdkManifestEntry `json:"items"`
	KeyFingerprint *string            `json:"key_fingerprint,omitempty"`
	Signature      *string            `json:"signature,omitempty"`
}

// SdkManifestEntry One row of the public SDK manifest.
type SdkManifestEntry struct {
	GitSha7 string `json:"git_sha7"`
	Lang    string `json:"lang"`
	Status  string `json:"status"`
	Version string `json:"version"`
}

// SdkManifestPubkey Public payload at “GET /v1/sdk/manifest/pubkey“.
type SdkManifestPubkey struct {
	Algorithm      *string `json:"algorithm,omitempty"`
	KeyFingerprint string  `json:"key_fingerprint"`
	PublicKey      string  `json:"public_key"`
}

// SessionAxes Known paid-session/v1 axes, preserving future minor-version additions.
type SessionAxes struct {
	Attachment           *SessionAxesAttachment `json:"attachment,omitempty"`
	DescriptorSchema     string                 `json:"descriptor_schema"`
	Metering             SessionAxesMetering    `json:"metering"`
	Refill               *SessionAxesRefill     `json:"refill,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SessionAxesAttachment defines model for SessionAxes.Attachment.
type SessionAxesAttachment string

// SessionAxesMetering defines model for SessionAxes.Metering.
type SessionAxesMetering string

// SessionAxesRefill defines model for SessionAxes.Refill.
type SessionAxesRefill string

// SessionAxesView Authoritative paid-session/v1 offering axes selected for the session.
type SessionAxesView struct {
	Attachment           *SessionAxesViewAttachment `json:"attachment,omitempty"`
	DescriptorSchema     string                     `json:"descriptor_schema"`
	Metering             SessionAxesViewMetering    `json:"metering"`
	Refill               *SessionAxesViewRefill     `json:"refill,omitempty"`
	AdditionalProperties map[string]interface{}     `json:"-"`
}

// SessionAxesViewAttachment defines model for SessionAxesView.Attachment.
type SessionAxesViewAttachment string

// SessionAxesViewMetering defines model for SessionAxesView.Metering.
type SessionAxesViewMetering string

// SessionAxesViewRefill defines model for SessionAxesView.Refill.
type SessionAxesViewRefill string

// SessionSettlementEnvelope defines model for SessionSettlementEnvelope.
type SessionSettlementEnvelope struct {
	Payload   map[string]interface{}     `json:"payload"`
	Signature SessionSettlementSignature `json:"signature"`
}

// SessionSettlementSignature defines model for SessionSettlementSignature.
type SessionSettlementSignature struct {
	Algorithm        SessionSettlementSignatureAlgorithm        `json:"algorithm"`
	Canonicalization SessionSettlementSignatureCanonicalization `json:"canonicalization"`
	Value            string                                     `json:"value"`
}

// SessionSettlementSignatureAlgorithm defines model for SessionSettlementSignature.Algorithm.
type SessionSettlementSignatureAlgorithm string

// SessionSettlementSignatureCanonicalization defines model for SessionSettlementSignature.Canonicalization.
type SessionSettlementSignatureCanonicalization string

// SessionStatusResponse Outbound: “GET /v1/sessions/{id}“.
//
// Customer-facing read-only view of a session's current state +
// running totals. Powers the SDK's “session.status“ callback and
// the portal's per-session detail page. Always-on; no auth beyond
// the standard CurrentApiKey ownership check.
//
// For active sessions, “cap_status“ carries the same shape the
// refill endpoint returns so portal UIs can show "how close to
// cap" without forcing a refill. For closed sessions, “cap_status“
// is omitted (irrelevant) and the close fields are populated.
type SessionStatusResponse struct {
	ActualUnits    *int               `json:"actual_units"`
	BilledValueWei int                `json:"billed_value_wei"`
	CapStatus      *CapStatus         `json:"cap_status"`
	Capability     string             `json:"capability"`
	ClosedAt       *time.Time         `json:"closed_at"`
	EstimatedUnits int                `json:"estimated_units"`
	FundedValueWei int                `json:"funded_value_wei"`
	MaxTotalUnits  int                `json:"max_total_units"`
	Offering       string             `json:"offering"`
	OpenedAt       time.Time          `json:"opened_at"`
	Outcome        *string            `json:"outcome"`
	Protocol       string             `json:"protocol"`
	RefillCount    int                `json:"refill_count"`
	SessionId      openapi_types.UUID `json:"session_id"`
	State          string             `json:"state"`
	WorkId         string             `json:"work_id"`
}

// SessionWithSdkList defines model for SessionWithSdkList.
type SessionWithSdkList struct {
	Items []SessionWithSdkView `json:"items"`
}

// SessionWithSdkView One row of the admin session-recent feed with the bucketed SDK
// approval status attached.
type SessionWithSdkView struct {
	ApiKeyId    openapi_types.UUID `json:"api_key_id"`
	Capability  string             `json:"capability"`
	ClosedAt    *time.Time         `json:"closed_at"`
	Offering    string             `json:"offering"`
	OpenedAt    time.Time          `json:"opened_at"`
	Protocol    string             `json:"protocol"`
	SdkIdentity *string            `json:"sdk_identity"`
	SdkStatus   string             `json:"sdk_status"`
	SessionId   openapi_types.UUID `json:"session_id"`
	State       string             `json:"state"`
	UserId      openapi_types.UUID `json:"user_id"`
	WorkId      string             `json:"work_id"`
}

// SettleJobRequest Inbound: “POST /v1/jobs/{id}/settle“.
//
// SDK reports the broker's terminal claim and the required signed
// “SettlementRecord“ from “Livepeer-Settlement“. “outcome“ is
// only an optional consistency assertion; signed settlement is
// authoritative for accounting.
type SettleJobRequest struct {
	ActualUnits int                `json:"actual_units"`
	BrokerJobId string             `json:"broker_job_id"`
	Outcome     *string            `json:"outcome,omitempty"`
	Settlement  SettlementEnvelope `json:"settlement"`
	WorkUnit    string             `json:"work_unit"`
}

// SettleJobResponse Outbound: “POST /v1/jobs/{id}/settle“.
//
// Final accounting for the job: what the customer was billed and
// how much encumbered value is being refunded, plus a fresh
// “cap_status“ snapshot. The cap_status here is informational —
// jobs are one-shot so “will_refuse_next_refill“ and
// “winddown_reason“ reflect whether the *next* mint of this
// size would be refused (e.g., spend-period cap is nearly full
// after this settlement). SDKs use it to surface "you're at N%
// of your monthly cap" UX after each completed job.
type SettleJobResponse struct {
	ActualUnits    int `json:"actual_units"`
	BilledValueWei int `json:"billed_value_wei"`

	// CapStatus Cap headroom snapshot returned with every successful refill.
	//
	// All percentages are in ``[0.0, 1.0]``. ``None`` means the cap
	// isn't enabled / configured (e.g., user has no spend-period cap
	// set, or operator-pool cap is opt-in and disabled).
	//
	// ``will_refuse_next_refill`` flips ``true`` when any enabled cap
	// is at or above the imminent-refusal threshold AND the projected
	// next-mint would push it over. SDK uses this to surface a
	// winddown warning to the customer one refill window early.
	//
	// ``winddown_reason`` is a short machine-readable string when
	// ``will_refuse_next_refill=true``: ``"session_cap_imminent"``,
	// ``"spend_period_cap_imminent"``, ``"user_balance_imminent"``,
	// ``"operator_pool_cap_imminent"``. ``None`` otherwise.
	CapStatus CapStatus          `json:"cap_status"`
	ClosedAt  time.Time          `json:"closed_at"`
	JobId     openapi_types.UUID `json:"job_id"`
	Outcome   string             `json:"outcome"`
	RefundWei int                `json:"refund_wei"`
	WorkId    string             `json:"work_id"`
}

// SettlementEnvelope defines model for SettlementEnvelope.
type SettlementEnvelope struct {
	Payload   map[string]interface{} `json:"payload"`
	Signature SettlementSignature    `json:"signature"`
}

// SettlementKey Cold-key-authorized broker key accepted for settlement signatures.
type SettlementKey struct {
	ExpiresAt time.Time `json:"expires_at"`

	// IntroducedInPublicationSeq Canonical decimal encoding of an unsigned 64-bit integer.
	IntroducedInPublicationSeq string    `json:"introduced_in_publication_seq"`
	NotBefore                  time.Time `json:"not_before"`
	PublicKey                  string    `json:"public_key"`
}

// SettlementSignature defines model for SettlementSignature.
type SettlementSignature struct {
	Algorithm        SettlementSignatureAlgorithm        `json:"algorithm"`
	Canonicalization SettlementSignatureCanonicalization `json:"canonicalization"`
	Value            string                              `json:"value"`
}

// SettlementSignatureAlgorithm defines model for SettlementSignature.Algorithm.
type SettlementSignatureAlgorithm string

// SettlementSignatureCanonicalization defines model for SettlementSignature.Canonicalization.
type SettlementSignatureCanonicalization string

// SignupRequest Inbound: “POST /v1/accounts/signup“.
type SignupRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignupResponse Outbound: “POST /v1/accounts/signup“ success.
type SignupResponse struct {
	// User Outbound: the public view of a user.
	User                 UserResponse `json:"user"`
	VerificationRequired *bool        `json:"verification_required,omitempty"`
}

// TopupRequest Admin-side topup body.
type TopupRequest struct {
	AmountWei int     `json:"amount_wei"`
	Kind      *string `json:"kind,omitempty"`
}

// TopupView Admin-side topup result.
type TopupView struct {
	CreatedAt     time.Time          `json:"created_at"`
	NewBalanceWei string             `json:"new_balance_wei"`
	TopupId       openapi_types.UUID `json:"topup_id"`
}

// UpdateNotificationPrefRequest Inbound: “PUT /v1/notifications/config“. One row at a time.
type UpdateNotificationPrefRequest struct {
	Channel string `json:"channel"`
	Enabled bool   `json:"enabled"`
	Trigger string `json:"trigger"`
}

// UpdateOperatorRequest Inbound: “PATCH /v1/admin/operators/{id}“ — at least one field.
type UpdateOperatorRequest struct {
	Name *string `json:"name,omitempty"`
	Role *string `json:"role,omitempty"`
}

// UpdateSdkApprovalRequest Inbound: “PATCH /v1/admin/sdk-approvals/{id}“ — at least one field.
type UpdateSdkApprovalRequest struct {
	Notes  *string `json:"notes,omitempty"`
	Status *string `json:"status,omitempty"`
}

// UserResponse Outbound: the public view of a user.
type UserResponse struct {
	Approved        bool                `json:"approved"`
	CreatedAt       time.Time           `json:"created_at"`
	Email           openapi_types.Email `json:"email"`
	EmailVerifiedAt *time.Time          `json:"email_verified_at"`
	Id              openapi_types.UUID  `json:"id"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for ValidationError.Loc.0.
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for ValidationError.Loc.1.
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// VerifyEmailRequest Inbound: “POST /v1/accounts/verify-email“.
type VerifyEmailRequest struct {
	Token string `json:"token"`
}

// WebhookAcceptedResponse The handler always returns 200 on accepted (or duplicate) events.
//
// Standard Webhooks senders interpret any non-2xx as a delivery
// failure and retry; we want explicit duplicate suppression to be
// transparent at the HTTP layer.
type WebhookAcceptedResponse struct {
	Duplicate       *bool   `json:"duplicate,omitempty"`
	Ok              *bool   `json:"ok,omitempty"`
	ReceivedEventId *string `json:"received_event_id,omitempty"`
}

// WebhookConfigCreated Outbound when the customer first registers a webhook URL.
// Carries the derived “secret“ exactly once — the customer
// must store it; LOC re-derives it on every send but never
// surfaces it again.
type WebhookConfigCreated struct {
	Secret string `json:"secret"`
	Url    string `json:"url"`
}

// WebhookConfigRequest Inbound: “PUT /v1/notifications/webhook“.
type WebhookConfigRequest struct {
	Url string `json:"url"`
}

// WebhookConfigView Public view of a user's webhook config — no secret material.
type WebhookConfigView struct {
	LastTestAt *time.Time `json:"last_test_at"`
	Url        string     `json:"url"`
}

// WebhookTestResult defines model for WebhookTestResult.
type WebhookTestResult struct {
	Detail *string `json:"detail,omitempty"`
	Ok     bool    `json:"ok"`
}

// WorkUnitEstimator Signed client-side funding-ceiling estimator declaration.
//
// LOC does not execute the estimator. It parses the registry boundary and
// relays the declaration so gateways can select their matching independent
// implementation.
type WorkUnitEstimator struct {
	Exactness string  `json:"exactness"`
	Fixtures  string  `json:"fixtures"`
	Id        string  `json:"id"`
	Package   *string `json:"package,omitempty"`
	Rounding  string  `json:"rounding"`
}

// MeEndpointV1AccountsMeGetParams defines parameters for MeEndpointV1AccountsMeGet.
type MeEndpointV1AccountsMeGetParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// ListApiKeysEndpointV1AccountsMeApiKeysGetParams defines parameters for ListApiKeysEndpointV1AccountsMeApiKeysGet.
type ListApiKeysEndpointV1AccountsMeApiKeysGetParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// CreateApiKeyEndpointV1AccountsMeApiKeysPostParams defines parameters for CreateApiKeyEndpointV1AccountsMeApiKeysPost.
type CreateApiKeyEndpointV1AccountsMeApiKeysPostParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// RevokeApiKeyEndpointV1AccountsMeApiKeysApiKeyIdDeleteParams defines parameters for RevokeApiKeyEndpointV1AccountsMeApiKeysApiKeyIdDelete.
type RevokeApiKeyEndpointV1AccountsMeApiKeysApiKeyIdDeleteParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// GetMyBalanceV1AccountsMeBalanceGetParams defines parameters for GetMyBalanceV1AccountsMeBalanceGet.
type GetMyBalanceV1AccountsMeBalanceGetParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// GetMyLedgerV1AccountsMeLedgerGetParams defines parameters for GetMyLedgerV1AccountsMeLedgerGet.
type GetMyLedgerV1AccountsMeLedgerGetParams struct {
	Limit                    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// PortalDownloadEndpointV1AccountsMeTelemetryDownloadGetParams defines parameters for PortalDownloadEndpointV1AccountsMeTelemetryDownloadGet.
type PortalDownloadEndpointV1AccountsMeTelemetryDownloadGetParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// PortalQueryEventsEndpointV1AccountsMeTelemetryEventsGetParams defines parameters for PortalQueryEventsEndpointV1AccountsMeTelemetryEventsGet.
type PortalQueryEventsEndpointV1AccountsMeTelemetryEventsGetParams struct {
	From                     string  `form:"from" json:"from"`
	To                       string  `form:"to" json:"to"`
	Type                     *string `form:"type,omitempty" json:"type,omitempty"`
	Cursor                   *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	PageSize                 *int    `form:"page_size,omitempty" json:"page_size,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// ListAuditEntriesEndpointV1AdminAuditGetParams defines parameters for ListAuditEntriesEndpointV1AdminAuditGet.
type ListAuditEntriesEndpointV1AdminAuditGetParams struct {
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// ListDepositSnapshotsEndpointV1AdminDepositSnapshotsGetParams defines parameters for ListDepositSnapshotsEndpointV1AdminDepositSnapshotsGet.
type ListDepositSnapshotsEndpointV1AdminDepositSnapshotsGetParams struct {
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// AdminListCapabilitiesEndpointV1AdminDiscoveryCapabilitiesGetParams defines parameters for AdminListCapabilitiesEndpointV1AdminDiscoveryCapabilitiesGet.
type AdminListCapabilitiesEndpointV1AdminDiscoveryCapabilitiesGetParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// AdminListOrchestratorsEndpointV1AdminDiscoveryOrchestratorsGetParams defines parameters for AdminListOrchestratorsEndpointV1AdminDiscoveryOrchestratorsGet.
type AdminListOrchestratorsEndpointV1AdminDiscoveryOrchestratorsGetParams struct {
	Capability    *string `form:"capability,omitempty" json:"capability,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// ListEmailEventsV1AdminEmailEventsGetParams defines parameters for ListEmailEventsV1AdminEmailEventsGet.
type ListEmailEventsV1AdminEmailEventsGetParams struct {
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// ListOperatorsEndpointV1AdminOperatorsGetParams defines parameters for ListOperatorsEndpointV1AdminOperatorsGet.
type ListOperatorsEndpointV1AdminOperatorsGetParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// CreateOperatorEndpointV1AdminOperatorsPostParams defines parameters for CreateOperatorEndpointV1AdminOperatorsPost.
type CreateOperatorEndpointV1AdminOperatorsPostParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateOperatorEndpointV1AdminOperatorsOperatorIdPatchParams defines parameters for UpdateOperatorEndpointV1AdminOperatorsOperatorIdPatch.
type UpdateOperatorEndpointV1AdminOperatorsOperatorIdPatchParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// RevokeOperatorEndpointV1AdminOperatorsOperatorIdRevokePostParams defines parameters for RevokeOperatorEndpointV1AdminOperatorsOperatorIdRevokePost.
type RevokeOperatorEndpointV1AdminOperatorsOperatorIdRevokePostParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// RotateOperatorTokenEndpointV1AdminOperatorsOperatorIdRotateTokenPostParams defines parameters for RotateOperatorTokenEndpointV1AdminOperatorsOperatorIdRotateTokenPost.
type RotateOperatorTokenEndpointV1AdminOperatorsOperatorIdRotateTokenPostParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListSdkApprovalsEndpointV1AdminSdkApprovalsGetParams defines parameters for ListSdkApprovalsEndpointV1AdminSdkApprovalsGet.
type ListSdkApprovalsEndpointV1AdminSdkApprovalsGetParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// CreateSdkApprovalEndpointV1AdminSdkApprovalsPostParams defines parameters for CreateSdkApprovalEndpointV1AdminSdkApprovalsPost.
type CreateSdkApprovalEndpointV1AdminSdkApprovalsPostParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// DeleteSdkApprovalEndpointV1AdminSdkApprovalsApprovalIdDeleteParams defines parameters for DeleteSdkApprovalEndpointV1AdminSdkApprovalsApprovalIdDelete.
type DeleteSdkApprovalEndpointV1AdminSdkApprovalsApprovalIdDeleteParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// UpdateSdkApprovalEndpointV1AdminSdkApprovalsApprovalIdPatchParams defines parameters for UpdateSdkApprovalEndpointV1AdminSdkApprovalsApprovalIdPatch.
type UpdateSdkApprovalEndpointV1AdminSdkApprovalsApprovalIdPatchParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// SdkDistributionEndpointV1AdminSdkDistributionGetParams defines parameters for SdkDistributionEndpointV1AdminSdkDistributionGet.
type SdkDistributionEndpointV1AdminSdkDistributionGetParams struct {
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// ListRecentSessionsEndpointV1AdminSessionsRecentGetParams defines parameters for ListRecentSessionsEndpointV1AdminSessionsRecentGet.
type ListRecentSessionsEndpointV1AdminSessionsRecentGetParams struct {
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// AdminEventCountsEndpointV1AdminTelemetryEventCountsGetParams defines parameters for AdminEventCountsEndpointV1AdminTelemetryEventCountsGet.
type AdminEventCountsEndpointV1AdminTelemetryEventCountsGetParams struct {
	Hours         *int    `form:"hours,omitempty" json:"hours,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// AdminRateLimitOffendersEndpointV1AdminTelemetryRateLimitOffendersGetParams defines parameters for AdminRateLimitOffendersEndpointV1AdminTelemetryRateLimitOffendersGet.
type AdminRateLimitOffendersEndpointV1AdminTelemetryRateLimitOffendersGetParams struct {
	Hours         *int    `form:"hours,omitempty" json:"hours,omitempty"`
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// AdminPurgeUserEndpointV1AdminTelemetryUsersUserIdDeleteParams defines parameters for AdminPurgeUserEndpointV1AdminTelemetryUsersUserIdDelete.
type AdminPurgeUserEndpointV1AdminTelemetryUsersUserIdDeleteParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListAllUsersEndpointV1AdminUsersGetParams defines parameters for ListAllUsersEndpointV1AdminUsersGet.
type ListAllUsersEndpointV1AdminUsersGetParams struct {
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset        *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// ListPendingUsersEndpointV1AdminUsersPendingGetParams defines parameters for ListPendingUsersEndpointV1AdminUsersPendingGet.
type ListPendingUsersEndpointV1AdminUsersPendingGetParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ApproveUserEndpointV1AdminUsersUserIdApprovePostParams defines parameters for ApproveUserEndpointV1AdminUsersUserIdApprovePost.
type ApproveUserEndpointV1AdminUsersUserIdApprovePostParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetBillingConfigEndpointV1AdminUsersUserIdBillingConfigGetParams defines parameters for GetBillingConfigEndpointV1AdminUsersUserIdBillingConfigGet.
type GetBillingConfigEndpointV1AdminUsersUserIdBillingConfigGetParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPutParams defines parameters for PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPut.
type PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPutParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ResendVerificationEndpointV1AdminUsersUserIdResendVerificationPostParams defines parameters for ResendVerificationEndpointV1AdminUsersUserIdResendVerificationPost.
type ResendVerificationEndpointV1AdminUsersUserIdResendVerificationPostParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// AdminTopupUserV1AdminUsersUserIdTopupPostParams defines parameters for AdminTopupUserV1AdminUsersUserIdTopupPost.
type AdminTopupUserV1AdminUsersUserIdTopupPostParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// LogoutEndpointV1AuthLogoutPostParams defines parameters for LogoutEndpointV1AuthLogoutPost.
type LogoutEndpointV1AuthLogoutPostParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// ListCapabilitiesEndpointV1CapabilitiesGetParams defines parameters for ListCapabilitiesEndpointV1CapabilitiesGet.
type ListCapabilitiesEndpointV1CapabilitiesGetParams struct {
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// OpenJobEndpointV1JobsPostParams defines parameters for OpenJobEndpointV1JobsPost.
type OpenJobEndpointV1JobsPostParams struct {
	IdempotencyKey               string  `json:"Idempotency-Key"`
	LivepeerOpenClearinghouseSDK *string `json:"Livepeer-Open-Clearinghouse-SDK,omitempty"`
	XAPIKey                      *string `json:"X-API-Key,omitempty"`
	Authorization                *string `json:"authorization,omitempty"`
}

// GetJobEndpointV1JobsJobIdGetParams defines parameters for GetJobEndpointV1JobsJobIdGet.
type GetJobEndpointV1JobsJobIdGetParams struct {
	XAPIKey       *string `json:"X-API-Key,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// SettleJobEndpointV1JobsJobIdSettlePostParams defines parameters for SettleJobEndpointV1JobsJobIdSettlePost.
type SettleJobEndpointV1JobsJobIdSettlePostParams struct {
	XAPIKey       *string `json:"X-API-Key,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// ListPortalNotificationsEndpointV1NotificationsGetParams defines parameters for ListPortalNotificationsEndpointV1NotificationsGet.
type ListPortalNotificationsEndpointV1NotificationsGetParams struct {
	Limit                    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// GetNotificationPrefsEndpointV1NotificationsConfigGetParams defines parameters for GetNotificationPrefsEndpointV1NotificationsConfigGet.
type GetNotificationPrefsEndpointV1NotificationsConfigGetParams struct {
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// PutNotificationPrefEndpointV1NotificationsConfigPutParams defines parameters for PutNotificationPrefEndpointV1NotificationsConfigPut.
type PutNotificationPrefEndpointV1NotificationsConfigPutParams struct {
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// DeleteWebhookConfigEndpointV1NotificationsWebhookDeleteParams defines parameters for DeleteWebhookConfigEndpointV1NotificationsWebhookDelete.
type DeleteWebhookConfigEndpointV1NotificationsWebhookDeleteParams struct {
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// GetWebhookConfigEndpointV1NotificationsWebhookGetParams defines parameters for GetWebhookConfigEndpointV1NotificationsWebhookGet.
type GetWebhookConfigEndpointV1NotificationsWebhookGetParams struct {
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// PutWebhookConfigEndpointV1NotificationsWebhookPutParams defines parameters for PutWebhookConfigEndpointV1NotificationsWebhookPut.
type PutWebhookConfigEndpointV1NotificationsWebhookPutParams struct {
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// TestWebhookConfigEndpointV1NotificationsWebhookTestPostParams defines parameters for TestWebhookConfigEndpointV1NotificationsWebhookTestPost.
type TestWebhookConfigEndpointV1NotificationsWebhookTestPostParams struct {
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// DismissPortalNotificationEndpointV1NotificationsNotificationIdDismissPostParams defines parameters for DismissPortalNotificationEndpointV1NotificationsNotificationIdDismissPost.
type DismissPortalNotificationEndpointV1NotificationsNotificationIdDismissPostParams struct {
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// ListOrchestratorsEndpointV1OrchestratorsGetParams defines parameters for ListOrchestratorsEndpointV1OrchestratorsGet.
type ListOrchestratorsEndpointV1OrchestratorsGetParams struct {
	Capability               *string `form:"capability,omitempty" json:"capability,omitempty"`
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// ListMyPaymentsV1PaymentsMeGetParams defines parameters for ListMyPaymentsV1PaymentsMeGet.
type ListMyPaymentsV1PaymentsMeGetParams struct {
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	XAPIKey       *string `json:"X-API-Key,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// GetPaymentEndpointV1PaymentsWorkIdGetParams defines parameters for GetPaymentEndpointV1PaymentsWorkIdGet.
type GetPaymentEndpointV1PaymentsWorkIdGetParams struct {
	XAPIKey       *string `json:"X-API-Key,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// SelectRouteEndpointV1RoutesGetParams defines parameters for SelectRouteEndpointV1RoutesGet.
type SelectRouteEndpointV1RoutesGetParams struct {
	Capability               string  `form:"capability" json:"capability"`
	Offering                 string  `form:"offering" json:"offering"`
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// OpenSessionEndpointV1SessionsPostParams defines parameters for OpenSessionEndpointV1SessionsPost.
type OpenSessionEndpointV1SessionsPostParams struct {
	IdempotencyKey               string  `json:"Idempotency-Key"`
	LivepeerOpenClearinghouseSDK *string `json:"Livepeer-Open-Clearinghouse-SDK,omitempty"`
	XAPIKey                      *string `json:"X-API-Key,omitempty"`
	Authorization                *string `json:"authorization,omitempty"`
}

// GetSessionStatusEndpointV1SessionsSessionIdGetParams defines parameters for GetSessionStatusEndpointV1SessionsSessionIdGet.
type GetSessionStatusEndpointV1SessionsSessionIdGetParams struct {
	XAPIKey       *string `json:"X-API-Key,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// CloseSessionEndpointV1SessionsSessionIdClosePostParams defines parameters for CloseSessionEndpointV1SessionsSessionIdClosePost.
type CloseSessionEndpointV1SessionsSessionIdClosePostParams struct {
	XAPIKey       *string `json:"X-API-Key,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// RefillSessionEndpointV1SessionsSessionIdRefillPostParams defines parameters for RefillSessionEndpointV1SessionsSessionIdRefillPost.
type RefillSessionEndpointV1SessionsSessionIdRefillPostParams struct {
	IdempotencyKey string  `json:"Idempotency-Key"`
	XAPIKey        *string `json:"X-API-Key,omitempty"`
	Authorization  *string `json:"authorization,omitempty"`
}

// IngestEndpointV1TelemetryPostParams defines parameters for IngestEndpointV1TelemetryPost.
type IngestEndpointV1TelemetryPostParams struct {
	XAPIKey       *string `json:"X-API-Key,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// QueryEventsEndpointV1TelemetryEventsGetParams defines parameters for QueryEventsEndpointV1TelemetryEventsGet.
type QueryEventsEndpointV1TelemetryEventsGetParams struct {
	// From ISO-8601 lower bound on received_ts.
	From string `form:"from" json:"from"`

	// To ISO-8601 upper bound on received_ts.
	To string `form:"to" json:"to"`

	// Type Glob over event_type. Only `*` is a wildcard.
	Type          *string                                              `form:"type,omitempty" json:"type,omitempty"`
	Format        *QueryEventsEndpointV1TelemetryEventsGetParamsFormat `form:"format,omitempty" json:"format,omitempty"`
	Cursor        *string                                              `form:"cursor,omitempty" json:"cursor,omitempty"`
	PageSize      *int                                                 `form:"page_size,omitempty" json:"page_size,omitempty"`
	XAPIKey       *string                                              `json:"X-API-Key,omitempty"`
	Authorization *string                                              `json:"authorization,omitempty"`
}

// QueryEventsEndpointV1TelemetryEventsGetParamsFormat defines parameters for QueryEventsEndpointV1TelemetryEventsGet.
type QueryEventsEndpointV1TelemetryEventsGetParamsFormat string

// ResendWebhookV1WebhooksResendPostParams defines parameters for ResendWebhookV1WebhooksResendPost.
type ResendWebhookV1WebhooksResendPostParams struct {
	WebhookId        *string `json:"webhook-id,omitempty"`
	WebhookTimestamp *string `json:"webhook-timestamp,omitempty"`
	WebhookSignature *string `json:"webhook-signature,omitempty"`
}

// CreateApiKeyEndpointV1AccountsMeApiKeysPostJSONRequestBody defines body for CreateApiKeyEndpointV1AccountsMeApiKeysPost for application/json ContentType.
type CreateApiKeyEndpointV1AccountsMeApiKeysPostJSONRequestBody = CreateApiKeyRequest

// SignupEndpointV1AccountsSignupPostJSONRequestBody defines body for SignupEndpointV1AccountsSignupPost for application/json ContentType.
type SignupEndpointV1AccountsSignupPostJSONRequestBody = SignupRequest

// VerifyEmailEndpointV1AccountsVerifyEmailPostJSONRequestBody defines body for VerifyEmailEndpointV1AccountsVerifyEmailPost for application/json ContentType.
type VerifyEmailEndpointV1AccountsVerifyEmailPostJSONRequestBody = VerifyEmailRequest

// CreateOperatorEndpointV1AdminOperatorsPostJSONRequestBody defines body for CreateOperatorEndpointV1AdminOperatorsPost for application/json ContentType.
type CreateOperatorEndpointV1AdminOperatorsPostJSONRequestBody = CreateOperatorRequest

// UpdateOperatorEndpointV1AdminOperatorsOperatorIdPatchJSONRequestBody defines body for UpdateOperatorEndpointV1AdminOperatorsOperatorIdPatch for application/json ContentType.
type UpdateOperatorEndpointV1AdminOperatorsOperatorIdPatchJSONRequestBody = UpdateOperatorRequest

// CreateSdkApprovalEndpointV1AdminSdkApprovalsPostJSONRequestBody defines body for CreateSdkApprovalEndpointV1AdminSdkApprovalsPost for application/json ContentType.
type CreateSdkApprovalEndpointV1AdminSdkApprovalsPostJSONRequestBody = CreateSdkApprovalRequest

// UpdateSdkApprovalEndpointV1AdminSdkApprovalsApprovalIdPatchJSONRequestBody defines body for UpdateSdkApprovalEndpointV1AdminSdkApprovalsApprovalIdPatch for application/json ContentType.
type UpdateSdkApprovalEndpointV1AdminSdkApprovalsApprovalIdPatchJSONRequestBody = UpdateSdkApprovalRequest

// PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPutJSONRequestBody defines body for PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPut for application/json ContentType.
type PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPutJSONRequestBody = BillingConfigUpdate

// AdminTopupUserV1AdminUsersUserIdTopupPostJSONRequestBody defines body for AdminTopupUserV1AdminUsersUserIdTopupPost for application/json ContentType.
type AdminTopupUserV1AdminUsersUserIdTopupPostJSONRequestBody = TopupRequest

// LoginEndpointV1AuthLoginPostJSONRequestBody defines body for LoginEndpointV1AuthLoginPost for application/json ContentType.
type LoginEndpointV1AuthLoginPostJSONRequestBody = LoginRequest

// ConfirmPasswordResetEndpointV1AuthPasswordResetConfirmPostJSONRequestBody defines body for ConfirmPasswordResetEndpointV1AuthPasswordResetConfirmPost for application/json ContentType.
type ConfirmPasswordResetEndpointV1AuthPasswordResetConfirmPostJSONRequestBody = ConfirmPasswordResetRequest

// RequestPasswordResetEndpointV1AuthPasswordResetRequestPostJSONRequestBody defines body for RequestPasswordResetEndpointV1AuthPasswordResetRequestPost for application/json ContentType.
type RequestPasswordResetEndpointV1AuthPasswordResetRequestPostJSONRequestBody = RequestPasswordResetRequest

// ResendVerificationEndpointV1AuthResendVerificationPostJSONRequestBody defines body for ResendVerificationEndpointV1AuthResendVerificationPost for application/json ContentType.
type ResendVerificationEndpointV1AuthResendVerificationPostJSONRequestBody = ResendVerificationRequest

// OpenJobEndpointV1JobsPostJSONRequestBody defines body for OpenJobEndpointV1JobsPost for application/json ContentType.
type OpenJobEndpointV1JobsPostJSONRequestBody = CreateJobRequest

// SettleJobEndpointV1JobsJobIdSettlePostJSONRequestBody defines body for SettleJobEndpointV1JobsJobIdSettlePost for application/json ContentType.
type SettleJobEndpointV1JobsJobIdSettlePostJSONRequestBody = SettleJobRequest

// PutNotificationPrefEndpointV1NotificationsConfigPutJSONRequestBody defines body for PutNotificationPrefEndpointV1NotificationsConfigPut for application/json ContentType.
type PutNotificationPrefEndpointV1NotificationsConfigPutJSONRequestBody = UpdateNotificationPrefRequest

// PutWebhookConfigEndpointV1NotificationsWebhookPutJSONRequestBody defines body for PutWebhookConfigEndpointV1NotificationsWebhookPut for application/json ContentType.
type PutWebhookConfigEndpointV1NotificationsWebhookPutJSONRequestBody = WebhookConfigRequest

// OpenSessionEndpointV1SessionsPostJSONRequestBody defines body for OpenSessionEndpointV1SessionsPost for application/json ContentType.
type OpenSessionEndpointV1SessionsPostJSONRequestBody = CreateSessionRequest

// CloseSessionEndpointV1SessionsSessionIdClosePostJSONRequestBody defines body for CloseSessionEndpointV1SessionsSessionIdClosePost for application/json ContentType.
type CloseSessionEndpointV1SessionsSessionIdClosePostJSONRequestBody = CloseSessionRequest

// RefillSessionEndpointV1SessionsSessionIdRefillPostJSONRequestBody defines body for RefillSessionEndpointV1SessionsSessionIdRefillPost for application/json ContentType.
type RefillSessionEndpointV1SessionsSessionIdRefillPostJSONRequestBody = RefillSessionRequest

// IngestEndpointV1TelemetryPostJSONRequestBody defines body for IngestEndpointV1TelemetryPost for application/json ContentType.
type IngestEndpointV1TelemetryPostJSONRequestBody = IngestRequest

// Getter for additional properties for JobAxes. Returns the specified
// element and whether it was found
func (a JobAxes) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for JobAxes
func (a *JobAxes) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for JobAxes to handle AdditionalProperties
func (a *JobAxes) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["transports"]; found {
		err = json.Unmarshal(raw, &a.Transports)
		if err != nil {
			return fmt.Errorf("error reading 'transports': %w", err)
		}
		delete(object, "transports")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for JobAxes to handle AdditionalProperties
func (a JobAxes) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Transports != nil {
		object["transports"], err = json.Marshal(a.Transports)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'transports': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SessionAxes. Returns the specified
// element and whether it was found
func (a SessionAxes) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SessionAxes
func (a *SessionAxes) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SessionAxes to handle AdditionalProperties
func (a *SessionAxes) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["attachment"]; found {
		err = json.Unmarshal(raw, &a.Attachment)
		if err != nil {
			return fmt.Errorf("error reading 'attachment': %w", err)
		}
		delete(object, "attachment")
	}

	if raw, found := object["descriptor_schema"]; found {
		err = json.Unmarshal(raw, &a.DescriptorSchema)
		if err != nil {
			return fmt.Errorf("error reading 'descriptor_schema': %w", err)
		}
		delete(object, "descriptor_schema")
	}

	if raw, found := object["metering"]; found {
		err = json.Unmarshal(raw, &a.Metering)
		if err != nil {
			return fmt.Errorf("error reading 'metering': %w", err)
		}
		delete(object, "metering")
	}

	if raw, found := object["refill"]; found {
		err = json.Unmarshal(raw, &a.Refill)
		if err != nil {
			return fmt.Errorf("error reading 'refill': %w", err)
		}
		delete(object, "refill")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SessionAxes to handle AdditionalProperties
func (a SessionAxes) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Attachment != nil {
		object["attachment"], err = json.Marshal(a.Attachment)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'attachment': %w", err)
		}
	}

	object["descriptor_schema"], err = json.Marshal(a.DescriptorSchema)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'descriptor_schema': %w", err)
	}

	object["metering"], err = json.Marshal(a.Metering)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metering': %w", err)
	}

	if a.Refill != nil {
		object["refill"], err = json.Marshal(a.Refill)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refill': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SessionAxesView. Returns the specified
// element and whether it was found
func (a SessionAxesView) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SessionAxesView
func (a *SessionAxesView) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SessionAxesView to handle AdditionalProperties
func (a *SessionAxesView) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["attachment"]; found {
		err = json.Unmarshal(raw, &a.Attachment)
		if err != nil {
			return fmt.Errorf("error reading 'attachment': %w", err)
		}
		delete(object, "attachment")
	}

	if raw, found := object["descriptor_schema"]; found {
		err = json.Unmarshal(raw, &a.DescriptorSchema)
		if err != nil {
			return fmt.Errorf("error reading 'descriptor_schema': %w", err)
		}
		delete(object, "descriptor_schema")
	}

	if raw, found := object["metering"]; found {
		err = json.Unmarshal(raw, &a.Metering)
		if err != nil {
			return fmt.Errorf("error reading 'metering': %w", err)
		}
		delete(object, "metering")
	}

	if raw, found := object["refill"]; found {
		err = json.Unmarshal(raw, &a.Refill)
		if err != nil {
			return fmt.Errorf("error reading 'refill': %w", err)
		}
		delete(object, "refill")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SessionAxesView to handle AdditionalProperties
func (a SessionAxesView) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Attachment != nil {
		object["attachment"], err = json.Marshal(a.Attachment)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'attachment': %w", err)
		}
	}

	object["descriptor_schema"], err = json.Marshal(a.DescriptorSchema)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'descriptor_schema': %w", err)
	}

	object["metering"], err = json.Marshal(a.Metering)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metering': %w", err)
	}

	if a.Refill != nil {
		object["refill"], err = json.Marshal(a.Refill)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refill': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
