// Package openclearinghouse provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openclearinghouse

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AdminUserList defines model for AdminUserList.
type AdminUserList struct {
	Items []AdminUserView `json:"items"`
	Total int             `json:"total"`
}

// AdminUserView Admin listing row: identity + approval + balance, no secrets.
type AdminUserView struct {
	Approved        bool               `json:"approved"`
	BalanceWei      int                `json:"balance_wei"`
	CreatedAt       time.Time          `json:"created_at"`
	Email           string             `json:"email"`
	EmailVerifiedAt *time.Time         `json:"email_verified_at"`
	Id              openapi_types.UUID `json:"id"`
}

// ApiKeyList Outbound: list of a user's keys.
type ApiKeyList struct {
	Items []ApiKeyView `json:"items"`
}

// ApiKeyView The non-secret view of a key.
type ApiKeyView struct {
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	Label      string             `json:"label"`
	LastUsedAt *time.Time         `json:"last_used_at"`
	Prefix     string             `json:"prefix"`
	RevokedAt  *time.Time         `json:"revoked_at"`
}

// ApprovedUserView A user with an active approval.
type ApprovedUserView struct {
	ApprovedAt time.Time          `json:"approved_at"`
	OperatorId openapi_types.UUID `json:"operator_id"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// AuditEntryList defines model for AuditEntryList.
type AuditEntryList struct {
	Items []AuditEntryView `json:"items"`
}

// AuditEntryView One row of operator_audit, joined with the operator + target emails.
type AuditEntryView struct {
	Action          string                  `json:"action"`
	CreatedAt       time.Time               `json:"created_at"`
	Id              openapi_types.UUID      `json:"id"`
	OperatorEmail   string                  `json:"operator_email"`
	Params          *map[string]interface{} `json:"params"`
	TargetUserEmail *string                 `json:"target_user_email"`
	TargetUserId    *openapi_types.UUID     `json:"target_user_id"`
}

// BalanceView The user-facing snapshot of credit state.
type BalanceView struct {
	AmountWei string             `json:"amount_wei"`
	UpdatedAt time.Time          `json:"updated_at"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// BillingConfigResponse Outbound: per-user config plus the effective values.
type BillingConfigResponse struct {
	// Config Per-user billing config (null = inherit default).
	Config BillingConfigView `json:"config"`

	// Effective The values that would be applied right now (overrides + defaults).
	Effective EffectiveBillingConfigView `json:"effective"`
}

// BillingConfigUpdate Inbound: “PUT /v1/admin/users/{id}/billing-config“.
//
// Send `null` to clear an override and inherit the default; send an
// integer to set/replace it.
type BillingConfigUpdate struct {
	AutoReplenishIncrementWei *int `json:"auto_replenish_increment_wei,omitempty"`
	AutoReplenishThresholdWei *int `json:"auto_replenish_threshold_wei,omitempty"`
	SpendPeriodCapWei         *int `json:"spend_period_cap_wei,omitempty"`
	SpendPeriodSeconds        *int `json:"spend_period_seconds,omitempty"`
}

// BillingConfigView Per-user billing config (null = inherit default).
type BillingConfigView struct {
	AutoReplenishIncrementWei *int               `json:"auto_replenish_increment_wei"`
	AutoReplenishThresholdWei *int               `json:"auto_replenish_threshold_wei"`
	SpendPeriodCapWei         *int               `json:"spend_period_cap_wei"`
	SpendPeriodSeconds        *int               `json:"spend_period_seconds"`
	UserId                    openapi_types.UUID `json:"user_id"`
}

// CapabilityList defines model for CapabilityList.
type CapabilityList struct {
	Items []CapabilityView `json:"items"`
}

// CapabilityView defines model for CapabilityView.
type CapabilityView struct {
	Name      string         `json:"name"`
	Offerings []OfferingView `json:"offerings"`
	WorkUnit  *string        `json:"work_unit"`
}

// ConfirmPasswordResetRequest Inbound: “POST /v1/auth/password-reset/confirm“.
type ConfirmPasswordResetRequest struct {
	NewPassword string `json:"new_password"`
	Token       string `json:"token"`
}

// CreateApiKeyRequest Inbound: “POST /v1/accounts/me/api-keys“.
type CreateApiKeyRequest struct {
	Label string `json:"label"`
}

// CreateApiKeyResponse Outbound: includes the raw key one time only.
type CreateApiKeyResponse struct {
	// Key The non-secret view of a key.
	Key ApiKeyView `json:"key"`

	// RawKey Shown only at creation; Livepeer Open Clearinghouse cannot recover it later
	RawKey string `json:"raw_key"`
}

// DepositSnapshotList defines model for DepositSnapshotList.
type DepositSnapshotList struct {
	Items []DepositSnapshotView `json:"items"`
}

// DepositSnapshotView One row from the periodic payment-daemon deposit poll.
type DepositSnapshotView struct {
	DepositWei    int                `json:"deposit_wei"`
	Id            openapi_types.UUID `json:"id"`
	ReserveWei    int                `json:"reserve_wei"`
	TakenAt       time.Time          `json:"taken_at"`
	WithdrawRound int                `json:"withdraw_round"`
}

// EffectiveBillingConfigView The values that would be applied right now (overrides + defaults).
type EffectiveBillingConfigView struct {
	AutoReplenishIncrementWei int `json:"auto_replenish_increment_wei"`
	AutoReplenishThresholdWei int `json:"auto_replenish_threshold_wei"`
	SpendPeriodCapWei         int `json:"spend_period_cap_wei"`
	SpendPeriodSeconds        int `json:"spend_period_seconds"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// LedgerEntryView One row of the credit ledger (audit history).
type LedgerEntryView struct {
	CreatedAt        time.Time           `json:"created_at"`
	DeltaWei         string              `json:"delta_wei"`
	Id               openapi_types.UUID  `json:"id"`
	Reason           string              `json:"reason"`
	RelatedPaymentId *openapi_types.UUID `json:"related_payment_id"`
	RelatedTopupId   *openapi_types.UUID `json:"related_topup_id"`
}

// LedgerPage defines model for LedgerPage.
type LedgerPage struct {
	Items []LedgerEntryView `json:"items"`
}

// LoginRequest Inbound: “POST /v1/auth/login“.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse Outbound: “POST /v1/auth/login“ success.
//
// The session token is delivered via cookie; the body just confirms.
type LoginResponse struct {
	// User Outbound: the public view of a user.
	User UserResponse `json:"user"`
}

// MintPaymentRequest Inbound: “POST /v1/payments/mint“.
type MintPaymentRequest struct {
	Capability string `json:"capability"`
	Offering   string `json:"offering"`
	WorkUnits  int    `json:"work_units"`
}

// MintPaymentResponse Outbound: “POST /v1/payments/mint“ success.
type MintPaymentResponse struct {
	Capability       string `json:"capability"`
	ExpectedValueWei string `json:"expected_value_wei"`
	FundedValueWei   string `json:"funded_value_wei"`
	Offering         string `json:"offering"`

	// PaymentBytes Base64-encoded; goes in Livepeer-Payment header
	PaymentBytes        string             `json:"payment_bytes"`
	PaymentId           openapi_types.UUID `json:"payment_id"`
	RecipientEthAddress string             `json:"recipient_eth_address"`
	WorkId              string             `json:"work_id"`
	WorkUnitsRequested  int                `json:"work_units_requested"`
}

// OfferingView defines model for OfferingView.
type OfferingView struct {
	Id                  string  `json:"id"`
	PricePerWorkUnitWei *string `json:"price_per_work_unit_wei"`
	WorkUnit            *string `json:"work_unit"`
}

// OrchestratorList defines model for OrchestratorList.
type OrchestratorList struct {
	Items []OrchestratorView `json:"items"`
}

// OrchestratorView defines model for OrchestratorView.
type OrchestratorView struct {
	Capabilities    []CapabilityView `json:"capabilities"`
	EthAddress      string           `json:"eth_address"`
	FreshnessStatus string           `json:"freshness_status"`
	SignatureStatus string           `json:"signature_status"`
	WorkerUrl       string           `json:"worker_url"`
}

// PaymentList defines model for PaymentList.
type PaymentList struct {
	Items []PaymentView `json:"items"`
}

// PaymentView Outbound: a single payment row in user-facing JSON.
type PaymentView struct {
	Capability          string             `json:"capability"`
	CreatedAt           time.Time          `json:"created_at"`
	ExpectedValueWei    string             `json:"expected_value_wei"`
	FundedValueWei      string             `json:"funded_value_wei"`
	Id                  openapi_types.UUID `json:"id"`
	Offering            string             `json:"offering"`
	RecipientEthAddress string             `json:"recipient_eth_address"`
	RefundedWei         string             `json:"refunded_wei"`
	ReservedWei         string             `json:"reserved_wei"`
	Status              string             `json:"status"`
	UpdatedAt           time.Time          `json:"updated_at"`
	WorkId              string             `json:"work_id"`
	WorkUnitsRequested  int                `json:"work_units_requested"`
}

// PendingUserList defines model for PendingUserList.
type PendingUserList struct {
	Items []PendingUserView `json:"items"`
}

// PendingUserView A user not yet approved.
type PendingUserView struct {
	CreatedAt       time.Time          `json:"created_at"`
	Email           string             `json:"email"`
	EmailVerifiedAt *time.Time         `json:"email_verified_at"`
	Id              openapi_types.UUID `json:"id"`
}

// ReportUsageRequest Inbound: “POST /v1/usage/report“.
//
// App developer self-reports the actuals for a previously-minted
// payment. The delta is refunded to their balance via the ledger.
type ReportUsageRequest struct {
	ActualWorkUnits int     `json:"actual_work_units"`
	RequestId       *string `json:"request_id,omitempty"`
	WorkId          string  `json:"work_id"`
}

// RequestPasswordResetRequest Inbound: “POST /v1/auth/password-reset/request“.
type RequestPasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// ResendVerificationRequest Inbound: “POST /v1/auth/resend-verification“.
type ResendVerificationRequest struct {
	Email openapi_types.Email `json:"email"`
}

// RouteView A single selected route — what `Select()` returns, web-flavored.
type RouteView struct {
	Capability          string `json:"capability"`
	EthAddress          string `json:"eth_address"`
	Offering            string `json:"offering"`
	PricePerWorkUnitWei string `json:"price_per_work_unit_wei"`
	QuoteId             string `json:"quote_id"`
	UnitsPerPrice       int    `json:"units_per_price"`
	WorkUnit            string `json:"work_unit"`
	WorkerUrl           string `json:"worker_url"`
}

// SignupRequest Inbound: “POST /v1/accounts/signup“.
type SignupRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignupResponse Outbound: “POST /v1/accounts/signup“ success.
type SignupResponse struct {
	// User Outbound: the public view of a user.
	User                 UserResponse `json:"user"`
	VerificationRequired *bool        `json:"verification_required,omitempty"`
}

// TopupRequest Admin-side topup body.
type TopupRequest struct {
	AmountWei int     `json:"amount_wei"`
	Kind      *string `json:"kind,omitempty"`
}

// TopupView Admin-side topup result.
type TopupView struct {
	CreatedAt     time.Time          `json:"created_at"`
	NewBalanceWei string             `json:"new_balance_wei"`
	TopupId       openapi_types.UUID `json:"topup_id"`
}

// UsageRecordView The persisted, first-write-wins reconciliation row.
type UsageRecordView struct {
	ActualCostWei   string             `json:"actual_cost_wei"`
	ActualWorkUnits int                `json:"actual_work_units"`
	CreatedAt       time.Time          `json:"created_at"`
	Id              openapi_types.UUID `json:"id"`
	PaymentId       openapi_types.UUID `json:"payment_id"`
	RequestId       *string            `json:"request_id"`
}

// UsageReportResponse Outbound: “POST /v1/usage/report“.
type UsageReportResponse struct {
	NewBalanceWei string `json:"new_balance_wei"`
	PaymentStatus string `json:"payment_status"`
	RefundedWei   string `json:"refunded_wei"`

	// Usage The persisted, first-write-wins reconciliation row.
	Usage UsageRecordView `json:"usage"`
}

// UserResponse Outbound: the public view of a user.
type UserResponse struct {
	Approved        bool                `json:"approved"`
	CreatedAt       time.Time           `json:"created_at"`
	Email           openapi_types.Email `json:"email"`
	EmailVerifiedAt *time.Time          `json:"email_verified_at"`
	Id              openapi_types.UUID  `json:"id"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// VerifyEmailRequest Inbound: “POST /v1/accounts/verify-email“.
type VerifyEmailRequest struct {
	Token string `json:"token"`
}

// MeEndpointV1AccountsMeGetParams defines parameters for MeEndpointV1AccountsMeGet.
type MeEndpointV1AccountsMeGetParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// ListApiKeysEndpointV1AccountsMeApiKeysGetParams defines parameters for ListApiKeysEndpointV1AccountsMeApiKeysGet.
type ListApiKeysEndpointV1AccountsMeApiKeysGetParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// CreateApiKeyEndpointV1AccountsMeApiKeysPostParams defines parameters for CreateApiKeyEndpointV1AccountsMeApiKeysPost.
type CreateApiKeyEndpointV1AccountsMeApiKeysPostParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// RevokeApiKeyEndpointV1AccountsMeApiKeysApiKeyIdDeleteParams defines parameters for RevokeApiKeyEndpointV1AccountsMeApiKeysApiKeyIdDelete.
type RevokeApiKeyEndpointV1AccountsMeApiKeysApiKeyIdDeleteParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// GetMyBalanceV1AccountsMeBalanceGetParams defines parameters for GetMyBalanceV1AccountsMeBalanceGet.
type GetMyBalanceV1AccountsMeBalanceGetParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// GetMyLedgerV1AccountsMeLedgerGetParams defines parameters for GetMyLedgerV1AccountsMeLedgerGet.
type GetMyLedgerV1AccountsMeLedgerGetParams struct {
	Limit                    *int    `form:"limit,omitempty" json:"limit,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// ListAuditEntriesEndpointV1AdminAuditGetParams defines parameters for ListAuditEntriesEndpointV1AdminAuditGet.
type ListAuditEntriesEndpointV1AdminAuditGetParams struct {
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// ListDepositSnapshotsEndpointV1AdminDepositSnapshotsGetParams defines parameters for ListDepositSnapshotsEndpointV1AdminDepositSnapshotsGet.
type ListDepositSnapshotsEndpointV1AdminDepositSnapshotsGetParams struct {
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// AdminListCapabilitiesEndpointV1AdminDiscoveryCapabilitiesGetParams defines parameters for AdminListCapabilitiesEndpointV1AdminDiscoveryCapabilitiesGet.
type AdminListCapabilitiesEndpointV1AdminDiscoveryCapabilitiesGetParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// AdminListOrchestratorsEndpointV1AdminDiscoveryOrchestratorsGetParams defines parameters for AdminListOrchestratorsEndpointV1AdminDiscoveryOrchestratorsGet.
type AdminListOrchestratorsEndpointV1AdminDiscoveryOrchestratorsGetParams struct {
	Capability    *string `form:"capability,omitempty" json:"capability,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// ListAllUsersEndpointV1AdminUsersGetParams defines parameters for ListAllUsersEndpointV1AdminUsersGet.
type ListAllUsersEndpointV1AdminUsersGetParams struct {
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset        *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// ListPendingUsersEndpointV1AdminUsersPendingGetParams defines parameters for ListPendingUsersEndpointV1AdminUsersPendingGet.
type ListPendingUsersEndpointV1AdminUsersPendingGetParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ApproveUserEndpointV1AdminUsersUserIdApprovePostParams defines parameters for ApproveUserEndpointV1AdminUsersUserIdApprovePost.
type ApproveUserEndpointV1AdminUsersUserIdApprovePostParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// GetBillingConfigEndpointV1AdminUsersUserIdBillingConfigGetParams defines parameters for GetBillingConfigEndpointV1AdminUsersUserIdBillingConfigGet.
type GetBillingConfigEndpointV1AdminUsersUserIdBillingConfigGetParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPutParams defines parameters for PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPut.
type PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPutParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ResendVerificationEndpointV1AdminUsersUserIdResendVerificationPostParams defines parameters for ResendVerificationEndpointV1AdminUsersUserIdResendVerificationPost.
type ResendVerificationEndpointV1AdminUsersUserIdResendVerificationPostParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// AdminTopupUserV1AdminUsersUserIdTopupPostParams defines parameters for AdminTopupUserV1AdminUsersUserIdTopupPost.
type AdminTopupUserV1AdminUsersUserIdTopupPostParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// LogoutEndpointV1AuthLogoutPostParams defines parameters for LogoutEndpointV1AuthLogoutPost.
type LogoutEndpointV1AuthLogoutPostParams struct {
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// ListCapabilitiesEndpointV1CapabilitiesGetParams defines parameters for ListCapabilitiesEndpointV1CapabilitiesGet.
type ListCapabilitiesEndpointV1CapabilitiesGetParams struct {
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// ListOrchestratorsEndpointV1OrchestratorsGetParams defines parameters for ListOrchestratorsEndpointV1OrchestratorsGet.
type ListOrchestratorsEndpointV1OrchestratorsGetParams struct {
	Capability               *string `form:"capability,omitempty" json:"capability,omitempty"`
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// ListMyPaymentsV1PaymentsMeGetParams defines parameters for ListMyPaymentsV1PaymentsMeGet.
type ListMyPaymentsV1PaymentsMeGetParams struct {
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	XAPIKey       *string `json:"X-API-Key,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// MintPaymentEndpointV1PaymentsMintPostParams defines parameters for MintPaymentEndpointV1PaymentsMintPost.
type MintPaymentEndpointV1PaymentsMintPostParams struct {
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
	XAPIKey        *string `json:"X-API-Key,omitempty"`
	Authorization  *string `json:"authorization,omitempty"`
}

// GetPaymentEndpointV1PaymentsWorkIdGetParams defines parameters for GetPaymentEndpointV1PaymentsWorkIdGet.
type GetPaymentEndpointV1PaymentsWorkIdGetParams struct {
	XAPIKey       *string `json:"X-API-Key,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// SelectRouteEndpointV1RoutesGetParams defines parameters for SelectRouteEndpointV1RoutesGet.
type SelectRouteEndpointV1RoutesGetParams struct {
	Capability               string  `form:"capability" json:"capability"`
	Offering                 string  `form:"offering" json:"offering"`
	XAPIKey                  *string `json:"X-API-Key,omitempty"`
	OpenClearinghouseSession *string `form:"open_clearinghouse_session,omitempty" json:"open_clearinghouse_session,omitempty"`
}

// ReportUsageEndpointV1UsageReportPostParams defines parameters for ReportUsageEndpointV1UsageReportPost.
type ReportUsageEndpointV1UsageReportPostParams struct {
	XAPIKey       *string `json:"X-API-Key,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// CreateApiKeyEndpointV1AccountsMeApiKeysPostJSONRequestBody defines body for CreateApiKeyEndpointV1AccountsMeApiKeysPost for application/json ContentType.
type CreateApiKeyEndpointV1AccountsMeApiKeysPostJSONRequestBody = CreateApiKeyRequest

// SignupEndpointV1AccountsSignupPostJSONRequestBody defines body for SignupEndpointV1AccountsSignupPost for application/json ContentType.
type SignupEndpointV1AccountsSignupPostJSONRequestBody = SignupRequest

// VerifyEmailEndpointV1AccountsVerifyEmailPostJSONRequestBody defines body for VerifyEmailEndpointV1AccountsVerifyEmailPost for application/json ContentType.
type VerifyEmailEndpointV1AccountsVerifyEmailPostJSONRequestBody = VerifyEmailRequest

// PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPutJSONRequestBody defines body for PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPut for application/json ContentType.
type PutBillingConfigEndpointV1AdminUsersUserIdBillingConfigPutJSONRequestBody = BillingConfigUpdate

// AdminTopupUserV1AdminUsersUserIdTopupPostJSONRequestBody defines body for AdminTopupUserV1AdminUsersUserIdTopupPost for application/json ContentType.
type AdminTopupUserV1AdminUsersUserIdTopupPostJSONRequestBody = TopupRequest

// LoginEndpointV1AuthLoginPostJSONRequestBody defines body for LoginEndpointV1AuthLoginPost for application/json ContentType.
type LoginEndpointV1AuthLoginPostJSONRequestBody = LoginRequest

// ConfirmPasswordResetEndpointV1AuthPasswordResetConfirmPostJSONRequestBody defines body for ConfirmPasswordResetEndpointV1AuthPasswordResetConfirmPost for application/json ContentType.
type ConfirmPasswordResetEndpointV1AuthPasswordResetConfirmPostJSONRequestBody = ConfirmPasswordResetRequest

// RequestPasswordResetEndpointV1AuthPasswordResetRequestPostJSONRequestBody defines body for RequestPasswordResetEndpointV1AuthPasswordResetRequestPost for application/json ContentType.
type RequestPasswordResetEndpointV1AuthPasswordResetRequestPostJSONRequestBody = RequestPasswordResetRequest

// ResendVerificationEndpointV1AuthResendVerificationPostJSONRequestBody defines body for ResendVerificationEndpointV1AuthResendVerificationPost for application/json ContentType.
type ResendVerificationEndpointV1AuthResendVerificationPostJSONRequestBody = ResendVerificationRequest

// MintPaymentEndpointV1PaymentsMintPostJSONRequestBody defines body for MintPaymentEndpointV1PaymentsMintPost for application/json ContentType.
type MintPaymentEndpointV1PaymentsMintPostJSONRequestBody = MintPaymentRequest

// ReportUsageEndpointV1UsageReportPostJSONRequestBody defines body for ReportUsageEndpointV1UsageReportPost for application/json ContentType.
type ReportUsageEndpointV1UsageReportPostJSONRequestBody = ReportUsageRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
