# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from livepeer.registry.v1 import resolver_pb2 as livepeer_dot_registry_dot_v1_dot_resolver__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in livepeer/registry/v1/resolver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResolverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveByAddress = channel.unary_unary(
                '/livepeer.registry.v1.Resolver/ResolveByAddress',
                request_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.ResolveByAddressRequest.SerializeToString,
                response_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.ResolveResult.FromString,
                _registered_method=True)
        self.Select = channel.unary_unary(
                '/livepeer.registry.v1.Resolver/Select',
                request_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectRequest.SerializeToString,
                response_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectResult.FromString,
                _registered_method=True)
        self.SelectMany = channel.unary_unary(
                '/livepeer.registry.v1.Resolver/SelectMany',
                request_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectRequest.SerializeToString,
                response_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectManyResult.FromString,
                _registered_method=True)
        self.ListKnown = channel.unary_unary(
                '/livepeer.registry.v1.Resolver/ListKnown',
                request_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.ListKnownRequest.SerializeToString,
                response_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.ListKnownResult.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/livepeer.registry.v1.Resolver/Refresh',
                request_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.RefreshRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetAuditLog = channel.unary_unary(
                '/livepeer.registry.v1.Resolver/GetAuditLog',
                request_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.GetAuditLogRequest.SerializeToString,
                response_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.AuditLogResult.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/livepeer.registry.v1.Resolver/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.HealthResult.FromString,
                _registered_method=True)


class ResolverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ResolveByAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Select(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectMany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKnown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveByAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveByAddress,
                    request_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.ResolveByAddressRequest.FromString,
                    response_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.ResolveResult.SerializeToString,
            ),
            'Select': grpc.unary_unary_rpc_method_handler(
                    servicer.Select,
                    request_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectRequest.FromString,
                    response_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectResult.SerializeToString,
            ),
            'SelectMany': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectMany,
                    request_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectRequest.FromString,
                    response_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectManyResult.SerializeToString,
            ),
            'ListKnown': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKnown,
                    request_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.ListKnownRequest.FromString,
                    response_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.ListKnownResult.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.RefreshRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetAuditLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditLog,
                    request_deserializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.GetAuditLogRequest.FromString,
                    response_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.AuditLogResult.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=livepeer_dot_registry_dot_v1_dot_resolver__pb2.HealthResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'livepeer.registry.v1.Resolver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('livepeer.registry.v1.Resolver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Resolver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResolveByAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.registry.v1.Resolver/ResolveByAddress',
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.ResolveByAddressRequest.SerializeToString,
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.ResolveResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Select(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.registry.v1.Resolver/Select',
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectRequest.SerializeToString,
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.registry.v1.Resolver/SelectMany',
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectRequest.SerializeToString,
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.SelectManyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKnown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.registry.v1.Resolver/ListKnown',
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.ListKnownRequest.SerializeToString,
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.ListKnownResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.registry.v1.Resolver/Refresh',
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.RefreshRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.registry.v1.Resolver/GetAuditLog',
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.GetAuditLogRequest.SerializeToString,
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.AuditLogResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/livepeer.registry.v1.Resolver/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            livepeer_dot_registry_dot_v1_dot_resolver__pb2.HealthResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
