# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-08-20T19:06:16+00:00

from __future__ import annotations

from typing import Any, Literal, TypedDict

from typing_extensions import NotRequired


class AdminUserView(TypedDict):
    id: str
    email: str
    email_verified_at: str | None
    approved: bool
    balance_wei: int
    created_at: str


class ApiKeyView(TypedDict):
    id: str
    prefix: str
    label: str
    created_at: str
    last_used_at: str | None
    revoked_at: str | None


class ApprovedUserView(TypedDict):
    user_id: str
    approved_at: str
    operator_id: str


class AuditEntryView(TypedDict):
    id: str
    operator_email: str
    action: str
    target_user_email: str | None
    target_user_id: str | None
    params: dict[str, Any] | None
    created_at: str


class BalanceView(TypedDict):
    user_id: str
    amount_wei: str
    updated_at: str


class BillingConfigUpdate(TypedDict):
    spend_period_seconds: NotRequired[int | None]
    spend_period_cap_wei: NotRequired[int | None]
    auto_replenish_increment_wei: NotRequired[int | None]
    auto_replenish_threshold_wei: NotRequired[int | None]


class BillingConfigView(TypedDict):
    user_id: str
    spend_period_seconds: int | None
    spend_period_cap_wei: int | None
    auto_replenish_increment_wei: int | None
    auto_replenish_threshold_wei: int | None


class CapStatus(TypedDict):
    session_pct_used: float
    spend_period_pct_used: NotRequired[float | None]
    user_balance_pct_used: NotRequired[float | None]
    operator_pool_pct_used: NotRequired[float | None]
    will_refuse_next_refill: bool
    winddown_reason: NotRequired[str | None]


class CloseSessionRequest(TypedDict):
    actual_units: int
    outcome: NotRequired[str | None]
    settlement: NotRequired[dict[str, Any] | None]


class CloseSessionResponse(TypedDict):
    session_id: str
    work_id: str
    actual_units: int
    billed_value_wei: int
    refund_wei: int
    outcome: str
    closed_at: str


class ConfirmPasswordResetRequest(TypedDict):
    token: str
    new_password: str


class CreateApiKeyRequest(TypedDict):
    label: str


class CreateApiKeyResponse(TypedDict):
    key: ApiKeyView
    raw_key: str


class CreateJobRequest(TypedDict):
    capability: str
    offering: str
    transport: Literal["unary", "stream", "multipart"]
    estimated_units: int
    max_total_units: NotRequired[int | None]


class CreateJobResponse(TypedDict):
    job_id: str
    request_id: str
    work_id: str
    broker_url: str
    protocol: str
    transport: Literal["unary", "stream", "multipart"]
    work_unit: str
    payment_envelope: str
    expected_value_wei: int
    funded_value_wei: int
    settle_endpoint: str
    opened_at: str


class CreateOperatorRequest(TypedDict):
    email: str
    name: str
    role: NotRequired[str]


class CreateSdkApprovalRequest(TypedDict):
    lang: str
    version: str
    git_sha7: str
    status: NotRequired[str]
    notes: NotRequired[str | None]


class CreateSessionRequest(TypedDict):
    capability: str
    offering: str
    estimated_runway_units: int
    max_total_units: int


class CreateSessionResponse(TypedDict):
    session_id: str
    request_id: str
    work_id: str
    broker_url: str
    protocol: str
    payment_envelope: str
    expected_value_wei: int
    funded_value_wei: int
    refill_endpoint: str
    close_endpoint: str
    opened_at: str


class DepositSnapshotView(TypedDict):
    id: str
    taken_at: str
    deposit_wei: int
    reserve_wei: int
    withdraw_round: int


class EffectiveBillingConfigView(TypedDict):
    spend_period_seconds: int
    spend_period_cap_wei: int
    auto_replenish_increment_wei: int
    auto_replenish_threshold_wei: int


class EmailEventView(TypedDict):
    id: str
    provider_event_id: str
    email_send_id: str | None
    provider_message_id: str | None
    event_type: str
    to_address: str | None
    received_at: str


class EventView(TypedDict):
    id: str
    event_type: str
    event_schema_version: int
    correlation_id: str | None
    client_ts: str | None
    received_ts: str
    source: str
    payload: dict[str, Any]


class IngestEventIn(TypedDict):
    event_type: str
    event_schema_version: int
    correlation_id: NotRequired[str | None]
    client_ts: NotRequired[str | None]
    payload: NotRequired[dict[str, Any]]


class IngestRequest(TypedDict):
    events: list[IngestEventIn]


class IngestResponse(TypedDict):
    accepted: int
    rejected: NotRequired[int]
    rejections: NotRequired[list[str]]


class JobAxes(TypedDict):
    transports: list[Literal["unary", "stream", "multipart"]]


class LedgerEntryView(TypedDict):
    id: str
    delta_wei: str
    reason: str
    related_payment_id: str | None
    related_topup_id: str | None
    created_at: str


class LedgerPage(TypedDict):
    items: list[LedgerEntryView]


class LoginRequest(TypedDict):
    email: str
    password: str


class NotificationPrefView(TypedDict):
    trigger: str
    channel: str
    enabled: bool
    is_default: bool


class NotificationPrefsResponse(TypedDict):
    items: list[NotificationPrefView]


class OperatorView(TypedDict):
    id: str
    email: str
    name: str
    role: str
    last_login_at: str | None
    revoked_at: str | None
    created_at: str


class OperatorWithToken(TypedDict):
    operator: OperatorView
    raw_token: str


class PaymentView(TypedDict):
    id: str
    work_id: str
    recipient_eth_address: str
    capability: str
    offering: str
    work_units_requested: int
    funded_value_wei: str
    expected_value_wei: str
    reserved_wei: str
    refunded_wei: str
    status: str
    created_at: str
    updated_at: str


class PendingUserView(TypedDict):
    id: str
    email: str
    email_verified_at: str | None
    created_at: str


class PortalNotificationView(TypedDict):
    id: str
    trigger: str
    body: dict[str, Any]
    fired_at: str
    dismissed_at: str | None


class RefillSessionRequest(TypedDict):
    observed_consumed_units: NotRequired[int | None]


class RefillSessionResponse(TypedDict):
    work_id: str
    refill_seq: int
    payment_envelope: str
    expected_value_wei: int
    funded_value_wei: int
    cap_status: CapStatus


class RequestPasswordResetRequest(TypedDict):
    email: str


class ResendVerificationRequest(TypedDict):
    email: str


class SdkApprovalView(TypedDict):
    id: str
    lang: str
    version: str
    git_sha7: str
    status: str
    notes: str | None
    added_by_operator_id: str | None
    created_at: str
    updated_at: str


class SdkDistributionEntry(TypedDict):
    sdk_identity: str
    count: int
    status: str


class SdkDistributionResponse(TypedDict):
    items: list[SdkDistributionEntry]


class SdkManifestEntry(TypedDict):
    lang: str
    version: str
    git_sha7: str
    status: str


class SdkManifestPubkey(TypedDict):
    public_key: str
    key_fingerprint: str
    algorithm: NotRequired[str]


class SessionAxes(TypedDict):
    descriptor_schema: str
    attachment: NotRequired[Literal["external", "inband-ws"]]
    metering: Literal["runner-reported", "broker-observed"]
    refill: NotRequired[Literal["extensible", "bounded"]]


class SessionStatusResponse(TypedDict):
    session_id: str
    work_id: str
    capability: str
    offering: str
    protocol: str
    state: str
    estimated_units: int
    max_total_units: int
    funded_value_wei: int
    billed_value_wei: int
    refill_count: int
    cap_status: CapStatus | None
    opened_at: str
    closed_at: str | None
    actual_units: int | None
    outcome: str | None


class SessionWithSdkView(TypedDict):
    session_id: str
    user_id: str
    api_key_id: str
    work_id: str
    capability: str
    offering: str
    protocol: str
    state: str
    sdk_identity: str | None
    sdk_status: str
    opened_at: str
    closed_at: str | None


class SettleJobRequest(TypedDict):
    actual_units: int
    broker_job_id: str
    work_unit: str
    outcome: NotRequired[str | None]
    settlement: NotRequired[dict[str, Any] | None]


class SettleJobResponse(TypedDict):
    job_id: str
    work_id: str
    actual_units: int
    billed_value_wei: int
    refund_wei: int
    outcome: str
    closed_at: str
    cap_status: CapStatus


class SignupRequest(TypedDict):
    email: str
    password: str


class TopupRequest(TypedDict):
    amount_wei: int
    kind: NotRequired[str]


class TopupView(TypedDict):
    topup_id: str
    new_balance_wei: str
    created_at: str


class UpdateNotificationPrefRequest(TypedDict):
    trigger: str
    channel: str
    enabled: bool


class UpdateOperatorRequest(TypedDict):
    name: NotRequired[str | None]
    role: NotRequired[str | None]


class UpdateSdkApprovalRequest(TypedDict):
    status: NotRequired[str | None]
    notes: NotRequired[str | None]


class UserResponse(TypedDict):
    id: str
    email: str
    email_verified_at: str | None
    approved: bool
    created_at: str


class ValidationError(TypedDict):
    loc: list[str | int]
    msg: str
    type: str
    input: NotRequired[Any]
    ctx: NotRequired[dict[str, Any]]


class VerifyEmailRequest(TypedDict):
    token: str


class WebhookAcceptedResponse(TypedDict):
    ok: NotRequired[bool]
    duplicate: NotRequired[bool]
    received_event_id: NotRequired[str | None]


class WebhookConfigCreated(TypedDict):
    url: str
    secret: str


class WebhookConfigRequest(TypedDict):
    url: str


class WebhookConfigView(TypedDict):
    url: str
    last_test_at: str | None


class WebhookTestResult(TypedDict):
    ok: bool
    detail: NotRequired[str | None]


class AdminUserList(TypedDict):
    items: list[AdminUserView]
    total: int


class ApiKeyList(TypedDict):
    items: list[ApiKeyView]


class AuditEntryList(TypedDict):
    items: list[AuditEntryView]


class BillingConfigResponse(TypedDict):
    config: BillingConfigView
    effective: EffectiveBillingConfigView


class DepositSnapshotList(TypedDict):
    items: list[DepositSnapshotView]


class EmailEventList(TypedDict):
    items: list[EmailEventView]


class EventList(TypedDict):
    items: list[EventView]
    next_cursor: NotRequired[str | None]


class HTTPValidationError(TypedDict):
    detail: NotRequired[list[ValidationError]]


class LoginResponse(TypedDict):
    user: UserResponse


class OfferingView(TypedDict):
    id: str
    price_per_work_unit_wei: str | None
    work_unit: str | None
    units_per_price: int
    protocol: str
    job: JobAxes | None
    session: SessionAxes | None
    extra: NotRequired[dict[str, Any]]


class OperatorList(TypedDict):
    items: list[OperatorView]


class PaymentList(TypedDict):
    items: list[PaymentView]


class PendingUserList(TypedDict):
    items: list[PendingUserView]


class PortalNotificationList(TypedDict):
    items: list[PortalNotificationView]


class RouteView(TypedDict):
    worker_url: str
    eth_address: str
    capability: str
    offering: str
    price_per_work_unit_wei: str
    work_unit: str
    units_per_price: int
    quote_id: str
    protocol: str
    job: JobAxes | None
    session: SessionAxes | None
    extra: NotRequired[dict[str, Any]]


class SdkApprovalList(TypedDict):
    items: list[SdkApprovalView]


class SdkManifest(TypedDict):
    items: list[SdkManifestEntry]
    generated_at: str
    signature: NotRequired[str | None]
    key_fingerprint: NotRequired[str | None]


class SessionWithSdkList(TypedDict):
    items: list[SessionWithSdkView]


class SignupResponse(TypedDict):
    user: UserResponse
    verification_required: NotRequired[bool]


class CapabilityView(TypedDict):
    name: str
    work_unit: str | None
    offerings: list[OfferingView]


class OrchestratorView(TypedDict):
    eth_address: str
    worker_url: str
    capabilities: list[CapabilityView]
    signature_status: str
    freshness_status: str


class CapabilityList(TypedDict):
    items: list[CapabilityView]


class OrchestratorList(TypedDict):
    items: list[OrchestratorView]
