# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-09-05T15:05:47+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Literal


@dataclass
class AdminUserView:
    id: str
    email: str
    email_verified_at: str | None
    approved: bool
    balance_wei: int
    created_at: str


@dataclass
class ApiKeyView:
    id: str
    prefix: str
    label: str
    created_at: str
    last_used_at: str | None
    revoked_at: str | None


@dataclass
class ApprovedUserView:
    user_id: str
    approved_at: str
    operator_id: str


@dataclass
class AuditEntryView:
    id: str
    operator_email: str
    action: str
    target_user_email: str | None
    target_user_id: str | None
    params: dict[str, Any] | None
    created_at: str


@dataclass
class BalanceView:
    user_id: str
    amount_wei: str
    updated_at: str


@dataclass
class BillingConfigUpdate:
    spend_period_seconds: int | None = None
    spend_period_cap_wei: int | None = None
    auto_replenish_increment_wei: int | None = None
    auto_replenish_threshold_wei: int | None = None


@dataclass
class BillingConfigView:
    user_id: str
    spend_period_seconds: int | None
    spend_period_cap_wei: int | None
    auto_replenish_increment_wei: int | None
    auto_replenish_threshold_wei: int | None


@dataclass
class CapStatus:
    session_pct_used: float
    will_refuse_next_refill: bool
    spend_period_pct_used: float | None = None
    user_balance_pct_used: float | None = None
    operator_pool_pct_used: float | None = None
    winddown_reason: str | None = None


@dataclass
class CloseSessionResponse:
    session_id: str
    work_id: str
    actual_units: int
    billed_value_wei: int
    refund_wei: int
    outcome: str
    closed_at: str


@dataclass
class ConfirmPasswordResetRequest:
    token: str
    new_password: str


@dataclass
class CreateApiKeyRequest:
    label: str


@dataclass
class CreateApiKeyResponse:
    key: ApiKeyView
    raw_key: str


class Transport(Enum):
    unary = "unary"
    stream = "stream"
    multipart = "multipart"


@dataclass
class CreateOperatorRequest:
    email: str
    name: str
    role: str | None = "member"


@dataclass
class CreateSdkApprovalRequest:
    lang: str
    version: str
    git_sha7: str
    status: str | None = "approved"
    notes: str | None = None


@dataclass
class DepositSnapshotView:
    id: str
    taken_at: str
    deposit_wei: int
    reserve_wei: int
    withdraw_round: int
    current_round: int | None
    ticket_validity_period: int | None
    ticket_validity_period_observed_at: str | None


@dataclass
class EffectiveBillingConfigView:
    spend_period_seconds: int
    spend_period_cap_wei: int
    auto_replenish_increment_wei: int
    auto_replenish_threshold_wei: int


@dataclass
class EmailEventView:
    id: str
    provider_event_id: str
    email_send_id: str | None
    provider_message_id: str | None
    event_type: str
    to_address: str | None
    received_at: str


@dataclass
class EventView:
    id: str
    event_type: str
    event_schema_version: int
    correlation_id: str | None
    client_ts: str | None
    received_ts: str
    source: str
    payload: dict[str, Any]


@dataclass
class IngestEventIn:
    event_type: str
    event_schema_version: int
    correlation_id: str | None = None
    client_ts: str | None = None
    payload: dict[str, Any] | None = None


@dataclass
class IngestRequest:
    events: list[IngestEventIn]


@dataclass
class IngestResponse:
    accepted: int
    rejected: int | None = 0
    rejections: list[str] | None = None


@dataclass
class JobAxes:
    transports: list[str]


class AccountingOutcome(Enum):
    unresolved = "unresolved"
    non_admission_audit = "non_admission_audit"
    broker_settled = "broker_settled"
    conservative_full_charge = "conservative_full_charge"


@dataclass
class JobStatusResponse:
    job_id: str
    request_id: str
    work_id: str
    state: str
    accounting_outcome: AccountingOutcome
    broker_exchange_outcome: str | None
    actual_units: int | None
    billed_value_wei: int | None
    funded_value_wei: int
    creation_round: int | None
    expires_after_round: int | None
    mint_ticket_validity_period: int | None
    mint_ticket_validity_period_observed_at: str | None
    observed_current_round: int | None
    current_ticket_validity_period: int | None
    current_ticket_validity_period_observed_at: str | None
    opened_at: str
    closed_at: str | None


@dataclass
class LedgerEntryView:
    id: str
    delta_wei: str
    reason: str
    related_payment_id: str | None
    related_topup_id: str | None
    created_at: str


@dataclass
class LedgerPage:
    items: list[LedgerEntryView]


@dataclass
class LoginRequest:
    email: str
    password: str


@dataclass
class NotificationPrefView:
    trigger: str
    channel: str
    enabled: bool
    is_default: bool


@dataclass
class NotificationPrefsResponse:
    items: list[NotificationPrefView]


@dataclass
class OperatorView:
    id: str
    email: str
    name: str
    role: str
    last_login_at: str | None
    revoked_at: str | None
    created_at: str


@dataclass
class OperatorWithToken:
    operator: OperatorView
    raw_token: str


@dataclass
class PaymentView:
    id: str
    work_id: str
    recipient_eth_address: str
    capability: str
    offering: str
    work_units_requested: int
    funded_value_wei: str
    expected_value_wei: str
    reserved_wei: str
    refunded_wei: str
    status: str
    created_at: str
    updated_at: str


@dataclass
class PendingUserView:
    id: str
    email: str
    email_verified_at: str | None
    created_at: str


@dataclass
class PortalNotificationView:
    id: str
    trigger: str
    body: dict[str, Any]
    fired_at: str
    dismissed_at: str | None


@dataclass
class RefillSessionRequest:
    observed_consumed_units: int | None = None
    rebind_from: str | None = None
    replaces_request_id: str | None = None


@dataclass
class RefillSessionResponse:
    work_id: str
    request_id: str
    refill_seq: int
    payment_envelope: str
    expected_value_wei: int
    funded_value_wei: int
    cap_status: CapStatus
    rebind_from: str | None = None


@dataclass
class RequestPasswordResetRequest:
    email: str


@dataclass
class ResendVerificationRequest:
    email: str


@dataclass
class RouteBinding:
    quote_id: str
    quote_version: str
    constraint_fingerprint: str
    route_fingerprint: str


class Protocol(Enum):
    paid_job_v1 = "paid-job/v1"
    paid_session_v1 = "paid-session/v1"


@dataclass
class SdkApprovalView:
    id: str
    lang: str
    version: str
    git_sha7: str
    status: str
    notes: str | None
    added_by_operator_id: str | None
    created_at: str
    updated_at: str


@dataclass
class SdkDistributionEntry:
    sdk_identity: str
    count: int
    status: str


@dataclass
class SdkDistributionResponse:
    items: list[SdkDistributionEntry]


@dataclass
class SdkManifestEntry:
    lang: str
    version: str
    git_sha7: str
    status: str


@dataclass
class SdkManifestPubkey:
    public_key: str
    key_fingerprint: str
    algorithm: str | None = "ed25519"


class Refill(Enum):
    extensible = "extensible"
    bounded = "bounded"


@dataclass
class SessionAxes:
    descriptor_schema: str
    metering: Literal["runner-reported"]
    attachment: Literal["external"] = "external"
    refill: Refill | None = Refill.extensible


@dataclass
class SessionAxesView:
    descriptor_schema: str
    metering: Literal["runner-reported"]
    attachment: Literal["external"] = "external"
    refill: Refill | None = Refill.extensible


@dataclass
class SessionSettlementSignature:
    algorithm: Literal["secp256k1"]
    canonicalization: Literal["jcs"]
    value: str


@dataclass
class SessionStatusResponse:
    session_id: str
    work_id: str
    capability: str
    offering: str
    protocol: str
    state: str
    estimated_units: int
    max_total_units: int
    funded_value_wei: int
    billed_value_wei: int
    refill_count: int
    cap_status: CapStatus | None
    opened_at: str
    closed_at: str | None
    actual_units: int | None
    outcome: str | None


@dataclass
class SessionWithSdkView:
    session_id: str
    user_id: str
    api_key_id: str
    work_id: str
    capability: str
    offering: str
    protocol: str
    state: str
    sdk_identity: str | None
    sdk_status: str
    opened_at: str
    closed_at: str | None


@dataclass
class SettleJobResponse:
    job_id: str
    work_id: str
    actual_units: int
    billed_value_wei: int
    refund_wei: int
    outcome: str
    closed_at: str
    cap_status: CapStatus


@dataclass
class SettlementKey:
    public_key: str
    not_before: str
    expires_at: str
    introduced_in_publication_seq: str


@dataclass
class SettlementSignature:
    algorithm: Literal["secp256k1"]
    canonicalization: Literal["jcs"]
    value: str


@dataclass
class SignupRequest:
    email: str
    password: str


@dataclass
class TopupRequest:
    amount_wei: int
    kind: str | None = "manual"


@dataclass
class TopupView:
    topup_id: str
    new_balance_wei: str
    created_at: str


@dataclass
class UpdateNotificationPrefRequest:
    trigger: str
    channel: str
    enabled: bool


@dataclass
class UpdateOperatorRequest:
    name: str | None = None
    role: str | None = None


@dataclass
class UpdateSdkApprovalRequest:
    status: str | None = None
    notes: str | None = None


@dataclass
class UserResponse:
    id: str
    email: str
    email_verified_at: str | None
    approved: bool
    created_at: str


@dataclass
class ValidationError:
    loc: list[str | int]
    msg: str
    type: str
    input: Any | None = None
    ctx: dict[str, Any] | None = None


@dataclass
class VerifyEmailRequest:
    token: str


@dataclass
class WebhookAcceptedResponse:
    ok: bool | None = True
    duplicate: bool | None = False
    received_event_id: str | None = None


@dataclass
class WebhookConfigCreated:
    url: str
    secret: str


@dataclass
class WebhookConfigRequest:
    url: str


@dataclass
class WebhookConfigView:
    url: str
    last_test_at: str | None


@dataclass
class WebhookTestResult:
    ok: bool
    detail: str | None = None


@dataclass
class WorkUnitEstimator:
    id: str
    rounding: str
    exactness: str
    fixtures: str
    package: str | None = None


@dataclass
class AdminUserList:
    items: list[AdminUserView]
    total: int


@dataclass
class ApiKeyList:
    items: list[ApiKeyView]


@dataclass
class AuditEntryList:
    items: list[AuditEntryView]


@dataclass
class BillingConfigResponse:
    config: BillingConfigView
    effective: EffectiveBillingConfigView


@dataclass
class CreateJobRequest:
    capability: str
    offering: str
    transport: Transport
    estimated_units: int
    max_total_units: int | None = None
    route_binding: RouteBinding | None = None


@dataclass
class CreateSessionRequest:
    capability: str
    offering: str
    descriptor_schema: str
    estimated_runway_units: int
    max_total_units: int
    session_params: dict[str, Any] | None = None
    route_binding: RouteBinding | None = None


@dataclass
class DepositSnapshotList:
    items: list[DepositSnapshotView]


@dataclass
class EmailEventList:
    items: list[EmailEventView]


@dataclass
class EventList:
    items: list[EventView]
    next_cursor: str | None = None


@dataclass
class HTTPValidationError:
    detail: list[ValidationError] | None = None


@dataclass
class LoginResponse:
    user: UserResponse


@dataclass
class OfferingView:
    id: str
    price_per_work_unit_wei: str | None
    work_unit: str | None
    units_per_price: str
    protocol: str
    work_unit_estimator: WorkUnitEstimator | None
    job: JobAxes | None
    session: SessionAxes | None
    extra: dict[str, Any] | None = None


@dataclass
class OperatorList:
    items: list[OperatorView]


@dataclass
class PaymentList:
    items: list[PaymentView]


@dataclass
class PendingUserList:
    items: list[PendingUserView]


@dataclass
class PortalNotificationList:
    items: list[PortalNotificationView]


@dataclass
class RouteSnapshot:
    broker_url: str
    eth_address: str
    capability: str
    offering: str
    protocol: Protocol
    work_unit: str
    price_per_work_unit_wei: str
    units_per_price: str
    quote_id: str
    quote_version: str
    constraint_fingerprint: str
    route_fingerprint: str
    settlement_keys: list[SettlementKey]
    schema_version: Literal["route-snapshot/v1"] = "route-snapshot/v1"
    work_unit_estimator: WorkUnitEstimator | None = None
    job: JobAxes | None = None
    session: SessionAxes | None = None
    extra: dict[str, Any] | None = None


@dataclass
class RouteView:
    worker_url: str
    eth_address: str
    capability: str
    offering: str
    price_per_work_unit_wei: str
    work_unit: str
    units_per_price: str
    quote_id: str
    quote_version: str
    constraint_fingerprint: str
    route_fingerprint: str
    protocol: str
    settlement_keys: list[SettlementKey]
    work_unit_estimator: WorkUnitEstimator | None
    job: JobAxes | None
    session: SessionAxes | None
    route_binding: RouteBinding
    route_snapshot: RouteSnapshot
    extra: dict[str, Any] | None = None


@dataclass
class SdkApprovalList:
    items: list[SdkApprovalView]


@dataclass
class SdkManifest:
    items: list[SdkManifestEntry]
    generated_at: str
    signature: str | None = None
    key_fingerprint: str | None = None


@dataclass
class SessionSettlementEnvelope:
    payload: dict[str, Any]
    signature: SessionSettlementSignature


@dataclass
class SessionWithSdkList:
    items: list[SessionWithSdkView]


@dataclass
class SettlementEnvelope:
    payload: dict[str, Any]
    signature: SettlementSignature


@dataclass
class SignupResponse:
    user: UserResponse
    verification_required: bool | None = True


@dataclass
class CapabilityView:
    name: str
    work_unit: str | None
    work_unit_estimator: WorkUnitEstimator | None
    offerings: list[OfferingView]


@dataclass
class CloseSessionRequest:
    actual_units: int
    settlement: SessionSettlementEnvelope
    outcome: str | None = None


@dataclass
class CreateJobResponse:
    job_id: str
    request_id: str
    work_id: str
    broker_url: str
    protocol: str
    transport: Transport
    work_unit: str
    route_snapshot: RouteSnapshot
    payment_envelope: str
    expected_value_wei: int
    funded_value_wei: int
    settle_endpoint: str
    opened_at: str


@dataclass
class CreateSessionResponse:
    session_id: str
    request_id: str
    work_id: str
    broker_url: str
    protocol: str
    session: SessionAxesView
    route_snapshot: RouteSnapshot
    payment_envelope: str
    expected_value_wei: int
    funded_value_wei: int
    refill_endpoint: str
    close_endpoint: str
    opened_at: str


@dataclass
class OrchestratorView:
    eth_address: str
    worker_url: str
    capabilities: list[CapabilityView]
    signature_status: str
    freshness_status: str


@dataclass
class SettleJobRequest:
    actual_units: int
    broker_job_id: str
    work_unit: str
    settlement: SettlementEnvelope
    outcome: str | None = None


@dataclass
class CapabilityList:
    items: list[CapabilityView]


@dataclass
class OrchestratorList:
    items: list[OrchestratorView]
