# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-05-23T13:35:28+00:00

from __future__ import annotations

from typing import Any, TypedDict

from typing_extensions import NotRequired


class AdminUserView(TypedDict):
    id: str
    email: str
    email_verified_at: str | None
    approved: bool
    balance_wei: int
    created_at: str


class ApiKeyView(TypedDict):
    id: str
    prefix: str
    label: str
    created_at: str
    last_used_at: str | None
    revoked_at: str | None


class ApprovedUserView(TypedDict):
    user_id: str
    approved_at: str
    operator_id: str


class AuditEntryView(TypedDict):
    id: str
    operator_email: str
    action: str
    target_user_email: str | None
    target_user_id: str | None
    params: dict[str, Any] | None
    created_at: str


class BalanceView(TypedDict):
    user_id: str
    amount_wei: str
    updated_at: str


class BillingConfigUpdate(TypedDict):
    spend_period_seconds: NotRequired[int | None]
    spend_period_cap_wei: NotRequired[int | None]
    auto_replenish_increment_wei: NotRequired[int | None]
    auto_replenish_threshold_wei: NotRequired[int | None]


class BillingConfigView(TypedDict):
    user_id: str
    spend_period_seconds: int | None
    spend_period_cap_wei: int | None
    auto_replenish_increment_wei: int | None
    auto_replenish_threshold_wei: int | None


class ConfirmPasswordResetRequest(TypedDict):
    token: str
    new_password: str


class CreateApiKeyRequest(TypedDict):
    label: str


class CreateApiKeyResponse(TypedDict):
    key: ApiKeyView
    raw_key: str


class DepositSnapshotView(TypedDict):
    id: str
    taken_at: str
    deposit_wei: int
    reserve_wei: int
    withdraw_round: int


class EffectiveBillingConfigView(TypedDict):
    spend_period_seconds: int
    spend_period_cap_wei: int
    auto_replenish_increment_wei: int
    auto_replenish_threshold_wei: int


class LedgerEntryView(TypedDict):
    id: str
    delta_wei: str
    reason: str
    related_payment_id: str | None
    related_topup_id: str | None
    created_at: str


class LedgerPage(TypedDict):
    items: list[LedgerEntryView]


class LoginRequest(TypedDict):
    email: str
    password: str


class MintPaymentRequest(TypedDict):
    capability: str
    offering: str
    work_units: int


class MintPaymentResponse(TypedDict):
    payment_id: str
    work_id: str
    payment_bytes: str
    expected_value_wei: str
    funded_value_wei: str
    recipient_eth_address: str
    capability: str
    offering: str
    work_units_requested: int


class OfferingView(TypedDict):
    id: str
    price_per_work_unit_wei: str | None
    work_unit: str | None


class PaymentView(TypedDict):
    id: str
    work_id: str
    recipient_eth_address: str
    capability: str
    offering: str
    work_units_requested: int
    funded_value_wei: str
    expected_value_wei: str
    reserved_wei: str
    refunded_wei: str
    status: str
    created_at: str
    updated_at: str


class PendingUserView(TypedDict):
    id: str
    email: str
    email_verified_at: str | None
    created_at: str


class ReportUsageRequest(TypedDict):
    work_id: str
    actual_work_units: int
    request_id: NotRequired[str | None]


class RequestPasswordResetRequest(TypedDict):
    email: str


class ResendVerificationRequest(TypedDict):
    email: str


class RouteView(TypedDict):
    worker_url: str
    eth_address: str
    capability: str
    offering: str
    price_per_work_unit_wei: str
    work_unit: str
    units_per_price: int
    quote_id: str


class SignupRequest(TypedDict):
    email: str
    password: str


class TopupRequest(TypedDict):
    amount_wei: int
    kind: NotRequired[str]


class TopupView(TypedDict):
    topup_id: str
    new_balance_wei: str
    created_at: str


class UsageRecordView(TypedDict):
    id: str
    payment_id: str
    actual_work_units: int
    actual_cost_wei: str
    request_id: str | None
    created_at: str


class UsageReportResponse(TypedDict):
    usage: UsageRecordView
    refunded_wei: str
    payment_status: str
    new_balance_wei: str


class UserResponse(TypedDict):
    id: str
    email: str
    email_verified_at: str | None
    approved: bool
    created_at: str


class ValidationError(TypedDict):
    loc: list[str | int]
    msg: str
    type: str
    input: NotRequired[Any]
    ctx: NotRequired[dict[str, Any]]


class VerifyEmailRequest(TypedDict):
    token: str


class AdminUserList(TypedDict):
    items: list[AdminUserView]
    total: int


class ApiKeyList(TypedDict):
    items: list[ApiKeyView]


class AuditEntryList(TypedDict):
    items: list[AuditEntryView]


class BillingConfigResponse(TypedDict):
    config: BillingConfigView
    effective: EffectiveBillingConfigView


class CapabilityView(TypedDict):
    name: str
    work_unit: str | None
    offerings: list[OfferingView]


class DepositSnapshotList(TypedDict):
    items: list[DepositSnapshotView]


class HTTPValidationError(TypedDict):
    detail: NotRequired[list[ValidationError]]


class LoginResponse(TypedDict):
    user: UserResponse


class OrchestratorView(TypedDict):
    eth_address: str
    worker_url: str
    capabilities: list[CapabilityView]
    signature_status: str
    freshness_status: str


class PaymentList(TypedDict):
    items: list[PaymentView]


class PendingUserList(TypedDict):
    items: list[PendingUserView]


class SignupResponse(TypedDict):
    user: UserResponse
    verification_required: NotRequired[bool]


class CapabilityList(TypedDict):
    items: list[CapabilityView]


class OrchestratorList(TypedDict):
    items: list[OrchestratorView]
